packages: []
catalogs:
  build:
    vite: ^6.4.1
  dev:
    '@astrojs/check': ^0.9.6
    bumpp: ^10.4.1
    pncat: ^0.10.4
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
  frontend:
    '@astrojs/vue': ^5.1.1
    '@unocss/astro': ^66.6.0
    '@unocss/preset-web-fonts': ^66.6.0
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.2.1
    unocss: ^66.6.0
    vue: ^3.5.28
  icons:
    '@iconify/json': ^2.2.439
  lint:
    '@octohash/eslint-config': ^0.2.2
    '@unocss/eslint-config': ^66.6.0
    eslint: ^9.39.2
    eslint-plugin-astro: ^1.6.0
    eslint-plugin-format: ^1.4.0
    lint-staged: ^16.2.7
    vue-tsc: ^3.2.4
  prod:
    '@astrojs/mdx': ^4.3.13
    '@astrojs/rss': ^4.0.14
    '@resvg/resvg-js': ^2.6.2
    astro: ^5.14.0
    beautiful-mermaid: ^0.1.3
    gh-statskit: ^0.0.0-alpha.1
    medium-zoom: ^1.1.0
    rehype-autolink-headings: ^7.1.0
    rehype-external-links: ^3.0.0
    rehype-slug: ^6.0.0
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.2.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@swc/core'
  - sharp
