packages: []
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.4
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.19.2
    vite: ^7.3.1
    vite-ssg: ^28.3.0
  dev:
    '@antfu/utils': ^9.3.0
    '@resvg/resvg-js': ^2.6.2
    '@shikijs/markdown-it': ^3.22.0
    bumpp: ^10.4.1
    feed: ^5.2.0
    gh-statskit: ^0.0.0-alpha.1
    gray-matter: ^4.0.3
    markdown-it: ^14.1.1
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.1
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^1.1.0
    pncat: ^0.10.2
    satori: ^0.19.2
    satori-html: ^0.3.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tinyglobby: ^0.2.15
    tsx: ^4.21.0
    typescript: ^5.9.3
  frontend:
    '@unhead/vue': ^2.1.4
    '@unocss/preset-web-fonts': ^66.6.0
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.2.1
    pinia: ^3.0.4
    unocss: ^66.6.0
    vue: ^3.5.28
    vue-router: ^5.0.2
  icons:
    '@iconify/json': ^2.2.439
  lint:
    '@octohash/eslint-config': ^0.2.2
    '@unocss/eslint-config': ^66.6.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.4.0
    lint-staged: ^16.2.7
    vue-tsc: ^3.2.4
  prod:
    beautiful-mermaid: ^0.1.3
    medium-zoom: ^1.1.0
    nprogress: ^0.2.0
  test:
    vitest: ^4.0.18
  types:
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^25.2.3
    '@types/nprogress': ^0.2.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@swc/core'
