packages: []
catalogs:
  build:
    vite: ^7.3.1
  dev:
    '@astrojs/check': ^0.9.6
    bumpp: ^10.4.1
    pncat: ^0.10.4
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
  frontend:
    '@astrojs/vue': ^5.1.4
    '@unocss/astro': ^66.6.2
    '@unocss/preset-web-fonts': ^66.6.2
    '@unocss/reset': ^66.6.2
    '@vue-flow/background': ^1.3.2
    '@vue-flow/core': ^1.48.2
    '@vueuse/core': ^14.2.1
    unocss: ^66.6.2
    vue: ^3.5.29
  icons:
    '@iconify/json': ^2.2.444
  lint:
    '@octohash/eslint-config': ^0.2.4
    '@unocss/eslint-config': ^66.6.2
    eslint: ^10.0.2
    eslint-plugin-astro: ^1.6.0
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.3.1
    vue-tsc: ^3.2.5
  prod:
    '@astrojs/mdx': ^4.3.13
    '@astrojs/rss': ^4.0.15
    '@resvg/resvg-js': ^2.6.2
    astro: ^5.18.0
    astro-expressive-code: ^0.41.7
    beautiful-mermaid: ^1.1.3
    elkjs: ^0.11.0
    gh-statskit: ^0.0.0-alpha.1
    medium-zoom: ^1.1.0
    rehype-autolink-headings: ^7.1.0
    rehype-external-links: ^3.0.0
    rehype-slug: ^6.0.0
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@swc/core'
  - sharp
  - vue-demi
