import type { AlgorithmRoadmapData } from '@/types'

const CHECKIN_TOPIC_SEQUENCE = [
  {
    id: 'two-pointer-linked',
    title: '链表双指针',
  },
  {
    id: 'prefix-sum',
    title: '前缀和',
  },
  {
    id: 'diff-array',
    title: '差分数组',
  },
  {
    id: '2d-array-ops',
    title: '二维数组',
  },
  {
    id: 'cycle-array',
    title: '循环数组',
  },
  {
    id: 'stack-queue',
    title: '栈与队列',
  },
  {
    id: 'hashing',
    title: '哈希',
  },
  {
    id: 'design',
    title: '设计',
  },
  {
    id: 'two-pointer-array',
    title: '数组双指针',
  },
  {
    id: 'sliding-window',
    title: '滑动窗口',
  },
  {
    id: 'binary-search',
    title: '二分搜索',
  },
  {
    id: 'random',
    title: '随机算法',
  },
  {
    id: 'recursion-ops',
    title: '递归',
  },
  {
    id: 'binary-tree',
    title: '二叉树',
  },
  {
    id: 'recursive-traverse',
    title: '递归遍历',
  },
  {
    id: 'level-order-traverse',
    title: '层序遍历',
  },
  {
    id: 'bst',
    title: '二叉搜索树',
  },
  {
    id: 'heap',
    title: '堆',
  },
  {
    id: 'trie',
    title: '字典树',
  },
  {
    id: 'backtracking',
    title: '回溯算法',
  },
  {
    id: 'dfs',
    title: '深度优先搜索',
  },
  {
    id: 'dp',
    title: '动态规划',
  },
  {
    id: 'divide-conquer',
    title: '分治算法',
  },
  {
    id: 'greedy',
    title: '贪心算法',
  },
  {
    id: 'bfs',
    title: '广度优先搜索',
  },
  {
    id: 'graph',
    title: '图',
  },
  {
    id: 'shortest-path',
    title: '最短路径',
  },
  {
    id: 'math',
    title: '数学',
  },
] as const

const CHECKIN_TOPIC_ORDER = new Map<string, number>(
  CHECKIN_TOPIC_SEQUENCE.map((topic, index) => [topic.id, index] as const),
)

const CHECKIN_TOPIC_TITLE = Object.fromEntries(
  CHECKIN_TOPIC_SEQUENCE.map(topic => [topic.id, topic.title]),
) as Record<string, string>

export const ALGORITHM_ROADMAP: AlgorithmRoadmapData = {
  version: 1,
  groups: [
    {
      id: 'array-operation-group',
      title: '数组操作',
    },
    {
      id: 'basic-ds-group',
      title: '基础数据结构',
    },
    {
      id: 'two-pointer-group',
      title: '双指针技巧',
    },
    {
      id: 'other-group',
      title: '其他算法',
    },
    {
      id: 'traverse-view-group',
      title: '遍历视角',
    },
    {
      id: 'subproblem-view-group',
      title: '子问题视角',
    },
    {
      id: 'advanced-ds-group',
      title: '高级数据结构',
    },
  ],
  topics: ([
    {
      id: 'diff-array',
      title: '差分数组',
      groupId: 'array-operation-group',
      difficulty: 'easy',
      problemIds: [
        'lc:370',
        'lc:1094',
        'lc:1109',
      ],
    },
    {
      id: '2d-array-ops',
      title: '二维数组',
      groupId: 'array-operation-group',
      difficulty: 'easy',
      problemIds: [
        'lc:48',
        'lc:54',
        'lc:59',
        'lc:61',
        'lc:151',
        'lc:lcr-146',
      ],
    },
    {
      id: 'prefix-sum',
      title: '前缀和',
      groupId: 'array-operation-group',
      difficulty: 'easy',
      problemIds: [
        'lc:238',
        'lc:303',
        'lc:304',
        'lc:523',
        'lc:525',
        'lc:560',
        'lc:724',
        'lc:974',
        'lc:1124',
        'lc:1314',
        'lc:1352',
      ],
    },
    {
      id: 'cycle-array',
      title: '循环数组',
      groupId: 'basic-ds-group',
      difficulty: 'easy',
      problemIds: [
        'lc:622',
        'lc:641',
        'lc:933',
        'lc:1670',
        'lc:2073',
      ],
    },
    {
      id: 'stack-queue',
      title: '栈与队列',
      groupId: 'basic-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:1',
        'lc:20',
        'lc:71',
        'lc:136',
        'lc:143',
        'lc:150',
        'lc:155',
        'lc:217',
        'lc:225',
        'lc:232',
        'lc:239',
        'lc:284',
        'lc:388',
        'lc:402',
        'lc:496',
        'lc:503',
        'lc:581',
        'lc:622',
        'lc:641',
        'lc:729',
        'lc:739',
        'lc:853',
        'lc:862',
        'lc:895',
        'lc:901',
        'lc:918',
        'lc:933',
        'lc:950',
        'lc:1019',
        'lc:1425',
        'lc:1438',
        'lc:1475',
        'lc:1670',
        'lc:1696',
        'lc:1700',
        'lc:1944',
        'lc:2073',
        'lc:lcr-184',
      ],
    },
    {
      id: 'hashing',
      title: '哈希',
      groupId: 'basic-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:1',
        'lc:15',
        'lc:18',
        'lc:49',
        'lc:128',
        'lc:133',
        'lc:138',
        'lc:167',
        'lc:169',
        'lc:242',
        'lc:290',
        'lc:387',
        'lc:389',
        'lc:442',
        'lc:448',
        'lc:519',
      ],
    },
    {
      id: 'design',
      title: '设计',
      groupId: 'basic-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:146',
        'lc:155',
        'lc:224',
        'lc:227',
        'lc:284',
        'lc:729',
        'lc:772',
        'lc:895',
        'lc:950',
        'lc:1670',
        'lc:1700',
      ],
    },
    {
      id: 'two-pointer-array',
      title: '数组双指针',
      groupId: 'two-pointer-group',
      difficulty: 'easy',
      problemIds: [
        'lc:1',
        'lc:5',
        'lc:11',
        'lc:14',
        'lc:15',
        'lc:18',
        'lc:26',
        'lc:27',
        'lc:42',
        'lc:75',
        'lc:80',
        'lc:83',
        'lc:88',
        'lc:125',
        'lc:167',
        'lc:283',
        'lc:344',
        'lc:867',
        'lc:912',
        'lc:977',
        'lc:1260',
        'lc:1329',
      ],
    },
    {
      id: 'sliding-window',
      title: '滑动窗口',
      groupId: 'two-pointer-group',
      difficulty: 'medium',
      problemIds: [
        'lc:3',
        'lc:76',
        'lc:209',
        'lc:219',
        'lc:220',
        'lc:395',
        'lc:424',
        'lc:438',
        'lc:567',
        'lc:713',
        'lc:1004',
        'lc:1658',
      ],
    },
    {
      id: 'binary-search',
      title: '二分搜索',
      groupId: 'two-pointer-group',
      difficulty: 'medium',
      problemIds: [
        'lc:33',
        'lc:34',
        'lc:35',
        'lc:74',
        'lc:81',
        'lc:162',
        'lc:240',
        'lc:392',
        'lc:410',
        'lc:566',
        'lc:658',
        'lc:704',
        'lc:792',
        'lc:852',
        'lc:875',
        'lc:1011',
        'lc:lcr-172',
      ],
    },
    {
      id: 'random',
      title: '随机算法',
      groupId: 'two-pointer-group',
      difficulty: 'medium',
      problemIds: [
        'lc:382',
        'lc:384',
        'lc:398',
        'lc:528',
      ],
    },
    {
      id: 'two-pointer-linked',
      title: '链表双指针',
      groupId: null,
      difficulty: 'easy',
      problemIds: [
        'lc:2',
        'lc:19',
        'lc:21',
        'lc:23',
        'lc:82',
        'lc:86',
        'lc:141',
        'lc:142',
        'lc:160',
        'lc:373',
        'lc:378',
        'lc:445',
        'lc:876',
        'lc:lcr-140',
      ],
    },
    {
      id: 'recursion-ops',
      title: '递归',
      groupId: null,
      difficulty: 'medium',
      problemIds: [
        'lc:25',
        'lc:92',
        'lc:206',
        'lc:234',
      ],
    },
    {
      id: 'binary-tree',
      title: '二叉树',
      groupId: null,
      difficulty: 'medium',
      problemIds: [
        'lc:94',
        'lc:102',
        'lc:104',
        'lc:111',
        'lc:144',
        'lc:145',
        'lc:222',
        'lc:429',
        'lc:543',
        'lc:589',
        'lc:590',
      ],
    },
    {
      id: 'recursive-traverse',
      title: '递归遍历',
      groupId: null,
      difficulty: 'medium',
      problemIds: [
        'lc:104',
        'lc:105',
        'lc:106',
        'lc:114',
        'lc:116',
        'lc:129',
        'lc:199',
        'lc:226',
        'lc:235',
        'lc:236',
        'lc:257',
        'lc:297',
        'lc:331',
        'lc:654',
        'lc:889',
        'lc:894',
        'lc:988',
        'lc:998',
        'lc:1022',
        'lc:1110',
        'lc:1457',
        'lc:1644',
        'lc:1650',
        'lc:1676',
      ],
    },
    {
      id: 'level-order-traverse',
      title: '层序遍历',
      groupId: null,
      difficulty: 'medium',
      problemIds: [
        'lc:94',
        'lc:102',
        'lc:103',
        'lc:107',
        'lc:117',
        'lc:144',
        'lc:145',
        'lc:515',
        'lc:637',
        'lc:662',
        'lc:958',
        'lc:1161',
        'lc:1302',
        'lc:1609',
      ],
    },
    {
      id: 'math',
      title: '数学',
      groupId: 'other-group',
      difficulty: 'medium',
      problemIds: [
        'lc:8',
        'lc:9',
        'lc:50',
        'lc:67',
        'lc:172',
        'lc:204',
        'lc:263',
        'lc:264',
        'lc:279',
        'lc:292',
        'lc:306',
        'lc:313',
        'lc:319',
        'lc:357',
        'lc:372',
        'lc:400',
        'lc:793',
        'lc:842',
        'lc:877',
        'lc:1201',
      ],
    },
    {
      id: 'greedy',
      title: '贪心算法',
      groupId: 'other-group',
      difficulty: 'medium',
      problemIds: [
        'lc:45',
        'lc:55',
        'lc:134',
        'lc:253',
        'lc:435',
        'lc:452',
        'lc:1235',
      ],
    },
    {
      id: 'dfs',
      title: '深度优先搜索',
      groupId: 'traverse-view-group',
      difficulty: 'hard',
      problemIds: [
        'lc:200',
        'lc:694',
        'lc:695',
        'lc:1020',
        'lc:1254',
        'lc:1905',
      ],
    },
    {
      id: 'backtracking',
      title: '回溯算法',
      groupId: 'traverse-view-group',
      difficulty: 'hard',
      problemIds: [
        'lc:17',
        'lc:37',
        'lc:39',
        'lc:40',
        'lc:46',
        'lc:47',
        'lc:51',
        'lc:52',
        'lc:77',
        'lc:78',
        'lc:79',
        'lc:89',
        'lc:90',
        'lc:93',
        'lc:131',
        'lc:216',
        'lc:473',
        'lc:491',
        'lc:526',
        'lc:967',
        'lc:980',
      ],
    },
    {
      id: 'divide-conquer',
      title: '分治算法',
      groupId: 'subproblem-view-group',
      difficulty: 'hard',
      problemIds: [
        'lc:23',
      ],
    },
    {
      id: 'dp',
      title: '动态规划',
      groupId: 'subproblem-view-group',
      difficulty: 'hard',
      problemIds: [
        'lc:53',
        'lc:72',
        'lc:198',
        'lc:213',
        'lc:300',
        'lc:322',
        'lc:337',
        'lc:354',
        'lc:416',
        'lc:494',
        'lc:509',
        'lc:516',
        'lc:518',
        'lc:583',
        'lc:712',
        'lc:931',
        'lc:1143',
        'lc:1312',
      ],
    },
    {
      id: 'bfs',
      title: '广度优先搜索',
      groupId: null,
      difficulty: 'hard',
      problemIds: [
        'lc:102',
        'lc:103',
        'lc:107',
        'lc:117',
        'lc:310',
        'lc:433',
        'lc:515',
        'lc:637',
        'lc:662',
        'lc:752',
        'lc:773',
        'lc:841',
        'lc:863',
        'lc:872',
        'lc:919',
        'lc:958',
        'lc:1091',
        'lc:1161',
        'lc:1302',
        'lc:1306',
        'lc:1609',
        'lc:1926',
      ],
    },
    {
      id: 'shortest-path',
      title: '最短路径',
      groupId: null,
      difficulty: 'hard',
      problemIds: [
        'lc:743',
        'lc:787',
        'lc:1368',
        'lc:1514',
        'lc:1631',
      ],
    },
    {
      id: 'bst',
      title: '二叉搜索树',
      groupId: 'advanced-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:95',
        'lc:96',
        'lc:98',
        'lc:230',
        'lc:450',
        'lc:538',
        'lc:700',
        'lc:701',
        'lc:1038',
        'lc:1373',
      ],
    },
    {
      id: 'heap',
      title: '堆',
      groupId: 'advanced-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:2',
        'lc:23',
        'lc:82',
        'lc:215',
        'lc:295',
        'lc:313',
        'lc:347',
        'lc:355',
        'lc:373',
        'lc:378',
        'lc:445',
        'lc:451',
        'lc:692',
        'lc:703',
        'lc:870',
        'lc:912',
        'lc:1834',
        'lc:1845',
      ],
    },
    {
      id: 'trie',
      title: '字典树',
      groupId: 'advanced-ds-group',
      difficulty: 'medium',
      problemIds: [
        'lc:208',
        'lc:211',
        'lc:648',
        'lc:677',
        'lc:1804',
      ],
    },
    {
      id: 'graph',
      title: '图',
      groupId: 'advanced-ds-group',
      difficulty: 'hard',
      problemIds: [
        'lc:1',
        'lc:49',
        'lc:128',
        'lc:130',
        'lc:133',
        'lc:138',
        'lc:169',
        'lc:207',
        'lc:210',
        'lc:242',
        'lc:261',
        'lc:290',
        'lc:323',
        'lc:387',
        'lc:389',
        'lc:442',
        'lc:448',
        'lc:519',
        'lc:547',
        'lc:785',
        'lc:886',
        'lc:947',
        'lc:990',
        'lc:1135',
        'lc:1361',
        'lc:1584',
      ],
    },
  ] as AlgorithmRoadmapData['topics'])
    .map(topic => ({
      ...topic,
      title: CHECKIN_TOPIC_TITLE[topic.id] ?? topic.title,
    }))
    .sort(
      (a, b) =>
        (CHECKIN_TOPIC_ORDER.get(a.id) ?? Number.MAX_SAFE_INTEGER)
        - (CHECKIN_TOPIC_ORDER.get(b.id) ?? Number.MAX_SAFE_INTEGER),
    ),
  edges: [
    {
      source: 'array-operation-group',
      target: 'two-pointer-group',
    },
    {
      source: 'array-operation-group',
      target: 'basic-ds-group',
    },
    {
      source: 'two-pointer-linked',
      target: 'recursion-ops',
    },
    {
      source: 'recursion-ops',
      target: 'binary-tree',
    },
    {
      source: 'binary-tree',
      target: 'recursive-traverse',
    },
    {
      source: 'binary-tree',
      target: 'level-order-traverse',
    },
    {
      source: 'binary-tree',
      target: 'advanced-ds-group',
    },
    {
      source: 'recursive-traverse',
      target: 'traverse-view-group',
    },
    {
      source: 'recursive-traverse',
      target: 'subproblem-view-group',
    },
    {
      source: 'level-order-traverse',
      target: 'bfs',
    },
    {
      source: 'bfs',
      target: 'shortest-path',
    },
  ],

  problems: {
    'lc:704': {
      id: 'lc:704',
      number: '704',
      slug: 'binary-search',
      title: 'Binary Search',
      difficulty: 'easy',
    },
    'lc:1109': {
      id: 'lc:1109',
      number: '1109',
      slug: 'corporate-flight-bookings',
      title: 'Corporate Flight Bookings',
      difficulty: 'medium',
    },
    'lc:1094': {
      id: 'lc:1094',
      number: '1094',
      slug: 'car-pooling',
      title: 'Car Pooling',
      difficulty: 'medium',
    },
    'lc:370': {
      id: 'lc:370',
      number: '370',
      slug: 'range-addition',
      title: 'Range Addition',
      difficulty: 'medium',
    },
    'lc:48': {
      id: 'lc:48',
      number: '48',
      slug: 'rotate-image',
      title: 'Rotate Image',
      difficulty: 'medium',
    },
    'lc:54': {
      id: 'lc:54',
      number: '54',
      slug: 'spiral-matrix',
      title: 'Spiral Matrix',
      difficulty: 'medium',
    },
    'lc:59': {
      id: 'lc:59',
      number: '59',
      slug: 'spiral-matrix-ii',
      title: 'Spiral Matrix II',
      difficulty: 'medium',
    },
    'lc:151': {
      id: 'lc:151',
      number: '151',
      slug: 'reverse-words-in-a-string',
      title: 'Reverse Words in a String',
      difficulty: 'medium',
    },
    'lc:61': {
      id: 'lc:61',
      number: '61',
      slug: 'rotate-list',
      title: 'Rotate List',
      difficulty: 'medium',
    },
    'lc:lcr-146': {
      id: 'lc:lcr-146',
      number: 'LCR 146',
      slug: 'shun-shi-zhen-da-yin-ju-zhen-lcof',
      title: '螺旋遍历二维数组',
      difficulty: 'easy',
    },
    'lc:1314': {
      id: 'lc:1314',
      number: '1314',
      slug: 'matrix-block-sum',
      title: 'Matrix Block Sum',
      difficulty: 'medium',
    },
    'lc:724': {
      id: 'lc:724',
      number: '724',
      slug: 'find-pivot-index',
      title: 'Find Pivot Index',
      difficulty: 'easy',
    },
    'lc:238': {
      id: 'lc:238',
      number: '238',
      slug: 'product-of-array-except-self',
      title: 'Product of Array Except Self',
      difficulty: 'medium',
    },
    'lc:1352': {
      id: 'lc:1352',
      number: '1352',
      slug: 'product-of-the-last-k-numbers',
      title: 'Product of the Last K Numbers',
      difficulty: 'medium',
    },
    'lc:525': {
      id: 'lc:525',
      number: '525',
      slug: 'contiguous-array',
      title: 'Contiguous Array',
      difficulty: 'medium',
    },
    'lc:523': {
      id: 'lc:523',
      number: '523',
      slug: 'continuous-subarray-sum',
      title: 'Continuous Subarray Sum',
      difficulty: 'medium',
    },
    'lc:560': {
      id: 'lc:560',
      number: '560',
      slug: 'subarray-sum-equals-k',
      title: 'Subarray Sum Equals K',
      difficulty: 'medium',
    },
    'lc:1124': {
      id: 'lc:1124',
      number: '1124',
      slug: 'longest-well-performing-interval',
      title: 'Longest Well-Performing Interval',
      difficulty: 'medium',
    },
    'lc:303': {
      id: 'lc:303',
      number: '303',
      slug: 'range-sum-query-immutable',
      title: 'Range Sum Query - Immutable',
      difficulty: 'easy',
    },
    'lc:304': {
      id: 'lc:304',
      number: '304',
      slug: 'range-sum-query-2d-immutable',
      title: 'Range Sum Query 2D - Immutable',
      difficulty: 'medium',
    },
    'lc:641': {
      id: 'lc:641',
      number: '641',
      slug: 'design-circular-deque',
      title: 'Design Circular Deque',
      difficulty: 'medium',
    },
    'lc:622': {
      id: 'lc:622',
      number: '622',
      slug: 'design-circular-queue',
      title: 'Design Circular Queue',
      difficulty: 'medium',
    },
    'lc:71': {
      id: 'lc:71',
      number: '71',
      slug: 'simplify-path',
      title: 'Simplify Path',
      difficulty: 'medium',
    },
    'lc:143': {
      id: 'lc:143',
      number: '143',
      slug: 'reorder-list',
      title: 'Reorder List',
      difficulty: 'medium',
    },
    'lc:20': {
      id: 'lc:20',
      number: '20',
      slug: 'valid-parentheses',
      title: 'Valid Parentheses',
      difficulty: 'easy',
    },
    'lc:150': {
      id: 'lc:150',
      number: '150',
      slug: 'evaluate-reverse-polish-notation',
      title: 'Evaluate Reverse Polish Notation',
      difficulty: 'medium',
    },
    'lc:225': {
      id: 'lc:225',
      number: '225',
      slug: 'implement-stack-using-queues',
      title: 'Implement Stack using Queues',
      difficulty: 'easy',
    },
    'lc:155': {
      id: 'lc:155',
      number: '155',
      slug: 'min-stack',
      title: 'Min Stack',
      difficulty: 'medium',
    },
    'lc:933': {
      id: 'lc:933',
      number: '933',
      slug: 'number-of-recent-calls',
      title: 'Number of Recent Calls',
      difficulty: 'easy',
    },
    'lc:2073': {
      id: 'lc:2073',
      number: '2073',
      slug: 'time-needed-to-buy-tickets',
      title: 'Time Needed to Buy Tickets',
      difficulty: 'easy',
    },
    'lc:1019': {
      id: 'lc:1019',
      number: '1019',
      slug: 'next-greater-node-in-linked-list',
      title: 'Next Greater Node In Linked List',
      difficulty: 'medium',
    },
    'lc:901': {
      id: 'lc:901',
      number: '901',
      slug: 'online-stock-span',
      title: 'Online Stock Span',
      difficulty: 'medium',
    },
    'lc:402': {
      id: 'lc:402',
      number: '402',
      slug: 'remove-k-digits',
      title: 'Remove K Digits',
      difficulty: 'medium',
    },
    'lc:853': {
      id: 'lc:853',
      number: '853',
      slug: 'car-fleet',
      title: 'Car Fleet',
      difficulty: 'medium',
    },
    'lc:1438': {
      id: 'lc:1438',
      number: '1438',
      slug: 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit',
      title: 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit',
      difficulty: 'medium',
    },
    'lc:862': {
      id: 'lc:862',
      number: '862',
      slug: 'shortest-subarray-with-sum-at-least-k',
      title: 'Shortest Subarray with Sum at Least K',
      difficulty: 'hard',
    },
    'lc:918': {
      id: 'lc:918',
      number: '918',
      slug: 'maximum-sum-circular-subarray',
      title: 'Maximum Sum Circular Subarray',
      difficulty: 'medium',
    },
    'lc:232': {
      id: 'lc:232',
      number: '232',
      slug: 'implement-queue-using-stacks',
      title: 'Implement Queue using Stacks',
      difficulty: 'easy',
    },
    'lc:496': {
      id: 'lc:496',
      number: '496',
      slug: 'next-greater-element-i',
      title: 'Next Greater Element I',
      difficulty: 'easy',
    },
    'lc:739': {
      id: 'lc:739',
      number: '739',
      slug: 'daily-temperatures',
      title: 'Daily Temperatures',
      difficulty: 'medium',
    },
    'lc:503': {
      id: 'lc:503',
      number: '503',
      slug: 'next-greater-element-ii',
      title: 'Next Greater Element II',
      difficulty: 'medium',
    },
    'lc:239': {
      id: 'lc:239',
      number: '239',
      slug: 'sliding-window-maximum',
      title: 'Sliding Window Maximum',
      difficulty: 'hard',
    },
    'lc:lcr-184': {
      id: 'lc:lcr-184',
      number: 'LCR 184',
      slug: 'dui-lie-de-zui-da-zhi-lcof',
      title: '设计自助结算系统',
      difficulty: 'medium',
    },
    'lc:1': {
      id: 'lc:1',
      number: '1',
      slug: 'two-sum',
      title: 'Two Sum',
      difficulty: 'easy',
    },
    'lc:128': {
      id: 'lc:128',
      number: '128',
      slug: 'longest-consecutive-sequence',
      title: 'Longest Consecutive Sequence',
      difficulty: 'medium',
    },
    'lc:290': {
      id: 'lc:290',
      number: '290',
      slug: 'word-pattern',
      title: 'Word Pattern',
      difficulty: 'easy',
    },
    'lc:138': {
      id: 'lc:138',
      number: '138',
      slug: 'copy-list-with-random-pointer',
      title: 'Copy List with Random Pointer',
      difficulty: 'medium',
    },
    'lc:133': {
      id: 'lc:133',
      number: '133',
      slug: 'clone-graph',
      title: 'Clone Graph',
      difficulty: 'medium',
    },
    'lc:242': {
      id: 'lc:242',
      number: '242',
      slug: 'valid-anagram',
      title: 'Valid Anagram',
      difficulty: 'easy',
    },
    'lc:49': {
      id: 'lc:49',
      number: '49',
      slug: 'group-anagrams',
      title: 'Group Anagrams',
      difficulty: 'medium',
    },
    'lc:387': {
      id: 'lc:387',
      number: '387',
      slug: 'first-unique-character-in-a-string',
      title: 'First Unique Character in a String',
      difficulty: 'easy',
    },
    'lc:169': {
      id: 'lc:169',
      number: '169',
      slug: 'majority-element',
      title: 'Majority Element',
      difficulty: 'easy',
    },
    'lc:729': {
      id: 'lc:729',
      number: '729',
      slug: 'my-calendar-i',
      title: 'My Calendar I',
      difficulty: 'medium',
    },
    'lc:950': {
      id: 'lc:950',
      number: '950',
      slug: 'reveal-cards-in-increasing-order',
      title: 'Reveal Cards In Increasing Order',
      difficulty: 'medium',
    },
    'lc:1700': {
      id: 'lc:1700',
      number: '1700',
      slug: 'number-of-students-unable-to-eat-lunch',
      title: 'Number of Students Unable to Eat Lunch',
      difficulty: 'easy',
    },
    'lc:224': {
      id: 'lc:224',
      number: '224',
      slug: 'basic-calculator',
      title: 'Basic Calculator',
      difficulty: 'hard',
    },
    'lc:227': {
      id: 'lc:227',
      number: '227',
      slug: 'basic-calculator-ii',
      title: 'Basic Calculator II',
      difficulty: 'medium',
    },
    'lc:772': {
      id: 'lc:772',
      number: '772',
      slug: 'basic-calculator-iii',
      title: 'Basic Calculator III',
      difficulty: 'hard',
    },
    'lc:146': {
      id: 'lc:146',
      number: '146',
      slug: 'lru-cache',
      title: 'LRU Cache',
      difficulty: 'medium',
    },
    'lc:80': {
      id: 'lc:80',
      number: '80',
      slug: 'remove-duplicates-from-sorted-array-ii',
      title: 'Remove Duplicates from Sorted Array II',
      difficulty: 'medium',
    },
    'lc:125': {
      id: 'lc:125',
      number: '125',
      slug: 'valid-palindrome',
      title: 'Valid Palindrome',
      difficulty: 'easy',
    },
    'lc:75': {
      id: 'lc:75',
      number: '75',
      slug: 'sort-colors',
      title: 'Sort Colors',
      difficulty: 'medium',
    },
    'lc:88': {
      id: 'lc:88',
      number: '88',
      slug: 'merge-sorted-array',
      title: 'Merge Sorted Array',
      difficulty: 'easy',
    },
    'lc:977': {
      id: 'lc:977',
      number: '977',
      slug: 'squares-of-a-sorted-array',
      title: 'Squares of a Sorted Array',
      difficulty: 'easy',
    },
    'lc:1329': {
      id: 'lc:1329',
      number: '1329',
      slug: 'sort-the-matrix-diagonally',
      title: 'Sort the Matrix Diagonally',
      difficulty: 'medium',
    },
    'lc:1260': {
      id: 'lc:1260',
      number: '1260',
      slug: 'shift-2d-grid',
      title: 'Shift 2D Grid',
      difficulty: 'easy',
    },
    'lc:867': {
      id: 'lc:867',
      number: '867',
      slug: 'transpose-matrix',
      title: 'Transpose Matrix',
      difficulty: 'easy',
    },
    'lc:14': {
      id: 'lc:14',
      number: '14',
      slug: 'longest-common-prefix',
      title: 'Longest Common Prefix',
      difficulty: 'easy',
    },
    'lc:26': {
      id: 'lc:26',
      number: '26',
      slug: 'remove-duplicates-from-sorted-array',
      title: 'Remove Duplicates from Sorted Array',
      difficulty: 'easy',
    },
    'lc:27': {
      id: 'lc:27',
      number: '27',
      slug: 'remove-element',
      title: 'Remove Element',
      difficulty: 'easy',
    },
    'lc:167': {
      id: 'lc:167',
      number: '167',
      slug: 'two-sum-ii-input-array-is-sorted',
      title: 'Two Sum II - Input Array Is Sorted',
      difficulty: 'medium',
    },
    'lc:5': {
      id: 'lc:5',
      number: '5',
      slug: 'longest-palindromic-substring',
      title: 'Longest Palindromic Substring',
      difficulty: 'medium',
    },
    'lc:83': {
      id: 'lc:83',
      number: '83',
      slug: 'remove-duplicates-from-sorted-list',
      title: 'Remove Duplicates from Sorted List',
      difficulty: 'easy',
    },
    'lc:283': {
      id: 'lc:283',
      number: '283',
      slug: 'move-zeroes',
      title: 'Move Zeroes',
      difficulty: 'easy',
    },
    'lc:344': {
      id: 'lc:344',
      number: '344',
      slug: 'reverse-string',
      title: 'Reverse String',
      difficulty: 'easy',
    },
    'lc:15': {
      id: 'lc:15',
      number: '15',
      slug: '3sum',
      title: '3Sum',
      difficulty: 'medium',
    },
    'lc:18': {
      id: 'lc:18',
      number: '18',
      slug: '4sum',
      title: '4Sum',
      difficulty: 'medium',
    },
    'lc:42': {
      id: 'lc:42',
      number: '42',
      slug: 'trapping-rain-water',
      title: 'Trapping Rain Water',
      difficulty: 'hard',
    },
    'lc:11': {
      id: 'lc:11',
      number: '11',
      slug: 'container-with-most-water',
      title: 'Container With Most Water',
      difficulty: 'medium',
    },
    'lc:1658': {
      id: 'lc:1658',
      number: '1658',
      slug: 'minimum-operations-to-reduce-x-to-zero',
      title: 'Minimum Operations to Reduce X to Zero',
      difficulty: 'medium',
    },
    'lc:713': {
      id: 'lc:713',
      number: '713',
      slug: 'subarray-product-less-than-k',
      title: 'Subarray Product Less Than K',
      difficulty: 'medium',
    },
    'lc:1004': {
      id: 'lc:1004',
      number: '1004',
      slug: 'max-consecutive-ones-iii',
      title: 'Max Consecutive Ones III',
      difficulty: 'medium',
    },
    'lc:424': {
      id: 'lc:424',
      number: '424',
      slug: 'longest-repeating-character-replacement',
      title: 'Longest Repeating Character Replacement',
      difficulty: 'medium',
    },
    'lc:219': {
      id: 'lc:219',
      number: '219',
      slug: 'contains-duplicate-ii',
      title: 'Contains Duplicate II',
      difficulty: 'easy',
    },
    'lc:209': {
      id: 'lc:209',
      number: '209',
      slug: 'minimum-size-subarray-sum',
      title: 'Minimum Size Subarray Sum',
      difficulty: 'medium',
    },
    'lc:76': {
      id: 'lc:76',
      number: '76',
      slug: 'minimum-window-substring',
      title: 'Minimum Window Substring',
      difficulty: 'hard',
    },
    'lc:567': {
      id: 'lc:567',
      number: '567',
      slug: 'permutation-in-string',
      title: 'Permutation in String',
      difficulty: 'medium',
    },
    'lc:438': {
      id: 'lc:438',
      number: '438',
      slug: 'find-all-anagrams-in-a-string',
      title: 'Find All Anagrams in a String',
      difficulty: 'medium',
    },
    'lc:3': {
      id: 'lc:3',
      number: '3',
      slug: 'longest-substring-without-repeating-characters',
      title: 'Longest Substring Without Repeating Characters',
      difficulty: 'medium',
    },
    'lc:566': {
      id: 'lc:566',
      number: '566',
      slug: 'reshape-the-matrix',
      title: 'Reshape the Matrix',
      difficulty: 'easy',
    },
    'lc:74': {
      id: 'lc:74',
      number: '74',
      slug: 'search-a-2d-matrix',
      title: 'Search a 2D Matrix',
      difficulty: 'medium',
    },
    'lc:240': {
      id: 'lc:240',
      number: '240',
      slug: 'search-a-2d-matrix-ii',
      title: 'Search a 2D Matrix II',
      difficulty: 'medium',
    },
    'lc:392': {
      id: 'lc:392',
      number: '392',
      slug: 'is-subsequence',
      title: 'Is Subsequence',
      difficulty: 'easy',
    },
    'lc:792': {
      id: 'lc:792',
      number: '792',
      slug: 'number-of-matching-subsequences',
      title: 'Number of Matching Subsequences',
      difficulty: 'medium',
    },
    'lc:658': {
      id: 'lc:658',
      number: '658',
      slug: 'find-k-closest-elements',
      title: 'Find K Closest Elements',
      difficulty: 'medium',
    },
    'lc:35': {
      id: 'lc:35',
      number: '35',
      slug: 'search-insert-position',
      title: 'Search Insert Position',
      difficulty: 'easy',
    },
    'lc:162': {
      id: 'lc:162',
      number: '162',
      slug: 'find-peak-element',
      title: 'Find Peak Element',
      difficulty: 'medium',
    },
    'lc:852': {
      id: 'lc:852',
      number: '852',
      slug: 'peak-index-in-a-mountain-array',
      title: 'Peak Index in a Mountain Array',
      difficulty: 'medium',
    },
    'lc:33': {
      id: 'lc:33',
      number: '33',
      slug: 'search-in-rotated-sorted-array',
      title: 'Search in Rotated Sorted Array',
      difficulty: 'medium',
    },
    'lc:81': {
      id: 'lc:81',
      number: '81',
      slug: 'search-in-rotated-sorted-array-ii',
      title: 'Search in Rotated Sorted Array II',
      difficulty: 'medium',
    },
    'lc:34': {
      id: 'lc:34',
      number: '34',
      slug: 'find-first-and-last-position-of-element-in-sorted-array',
      title: 'Find First and Last Position of Element in Sorted Array',
      difficulty: 'medium',
    },
    'lc:lcr-172': {
      id: 'lc:lcr-172',
      number: 'LCR 172',
      slug: 'zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof',
      title: '统计目标成绩的出现次数',
      difficulty: 'easy',
    },
    'lc:875': {
      id: 'lc:875',
      number: '875',
      slug: 'koko-eating-bananas',
      title: 'Koko Eating Bananas',
      difficulty: 'medium',
    },
    'lc:1011': {
      id: 'lc:1011',
      number: '1011',
      slug: 'capacity-to-ship-packages-within-d-days',
      title: 'Capacity To Ship Packages Within D Days',
      difficulty: 'medium',
    },
    'lc:410': {
      id: 'lc:410',
      number: '410',
      slug: 'split-array-largest-sum',
      title: 'Split Array Largest Sum',
      difficulty: 'hard',
    },
    'lc:528': {
      id: 'lc:528',
      number: '528',
      slug: 'random-pick-with-weight',
      title: 'Random Pick with Weight',
      difficulty: 'medium',
    },
    'lc:382': {
      id: 'lc:382',
      number: '382',
      slug: 'linked-list-random-node',
      title: 'Linked List Random Node',
      difficulty: 'medium',
    },
    'lc:398': {
      id: 'lc:398',
      number: '398',
      slug: 'random-pick-index',
      title: 'Random Pick Index',
      difficulty: 'medium',
    },
    'lc:384': {
      id: 'lc:384',
      number: '384',
      slug: 'shuffle-an-array',
      title: 'Shuffle an Array',
      difficulty: 'medium',
    },
    'lc:82': {
      id: 'lc:82',
      number: '82',
      slug: 'remove-duplicates-from-sorted-list-ii',
      title: 'Remove Duplicates from Sorted List II',
      difficulty: 'medium',
    },
    'lc:378': {
      id: 'lc:378',
      number: '378',
      slug: 'kth-smallest-element-in-a-sorted-matrix',
      title: 'Kth Smallest Element in a Sorted Matrix',
      difficulty: 'medium',
    },
    'lc:373': {
      id: 'lc:373',
      number: '373',
      slug: 'find-k-pairs-with-smallest-sums',
      title: 'Find K Pairs with Smallest Sums',
      difficulty: 'medium',
    },
    'lc:2': {
      id: 'lc:2',
      number: '2',
      slug: 'add-two-numbers',
      title: 'Add Two Numbers',
      difficulty: 'medium',
    },
    'lc:445': {
      id: 'lc:445',
      number: '445',
      slug: 'add-two-numbers-ii',
      title: 'Add Two Numbers II',
      difficulty: 'medium',
    },
    'lc:21': {
      id: 'lc:21',
      number: '21',
      slug: 'merge-two-sorted-lists',
      title: 'Merge Two Sorted Lists',
      difficulty: 'easy',
    },
    'lc:86': {
      id: 'lc:86',
      number: '86',
      slug: 'partition-list',
      title: 'Partition List',
      difficulty: 'medium',
    },
    'lc:23': {
      id: 'lc:23',
      number: '23',
      slug: 'merge-k-sorted-lists',
      title: 'Merge k Sorted Lists',
      difficulty: 'hard',
    },
    'lc:19': {
      id: 'lc:19',
      number: '19',
      slug: 'remove-nth-node-from-end-of-list',
      title: 'Remove Nth Node From End of List',
      difficulty: 'medium',
    },
    'lc:876': {
      id: 'lc:876',
      number: '876',
      slug: 'middle-of-the-linked-list',
      title: 'Middle of the Linked List',
      difficulty: 'easy',
    },
    'lc:142': {
      id: 'lc:142',
      number: '142',
      slug: 'linked-list-cycle-ii',
      title: 'Linked List Cycle II',
      difficulty: 'medium',
    },
    'lc:160': {
      id: 'lc:160',
      number: '160',
      slug: 'intersection-of-two-linked-lists',
      title: 'Intersection of Two Linked Lists',
      difficulty: 'easy',
    },
    'lc:141': {
      id: 'lc:141',
      number: '141',
      slug: 'linked-list-cycle',
      title: 'Linked List Cycle',
      difficulty: 'easy',
    },
    'lc:lcr-140': {
      id: 'lc:lcr-140',
      number: 'LCR 140',
      slug: 'lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof',
      title: '训练计划 II',
      difficulty: 'easy',
    },
    'lc:206': {
      id: 'lc:206',
      number: '206',
      slug: 'reverse-linked-list',
      title: 'Reverse Linked List',
      difficulty: 'easy',
    },
    'lc:92': {
      id: 'lc:92',
      number: '92',
      slug: 'reverse-linked-list-ii',
      title: 'Reverse Linked List II',
      difficulty: 'medium',
    },
    'lc:25': {
      id: 'lc:25',
      number: '25',
      slug: 'reverse-nodes-in-k-group',
      title: 'Reverse Nodes in k-Group',
      difficulty: 'hard',
    },
    'lc:234': {
      id: 'lc:234',
      number: '234',
      slug: 'palindrome-linked-list',
      title: 'Palindrome Linked List',
      difficulty: 'easy',
    },
    'lc:144': {
      id: 'lc:144',
      number: '144',
      slug: 'binary-tree-preorder-traversal',
      title: 'Binary Tree Preorder Traversal',
      difficulty: 'easy',
    },
    'lc:94': {
      id: 'lc:94',
      number: '94',
      slug: 'binary-tree-inorder-traversal',
      title: 'Binary Tree Inorder Traversal',
      difficulty: 'easy',
    },
    'lc:145': {
      id: 'lc:145',
      number: '145',
      slug: 'binary-tree-postorder-traversal',
      title: 'Binary Tree Postorder Traversal',
      difficulty: 'easy',
    },
    'lc:102': {
      id: 'lc:102',
      number: '102',
      slug: 'binary-tree-level-order-traversal',
      title: 'Binary Tree Level Order Traversal',
      difficulty: 'medium',
    },
    'lc:589': {
      id: 'lc:589',
      number: '589',
      slug: 'n-ary-tree-preorder-traversal',
      title: 'N-ary Tree Preorder Traversal',
      difficulty: 'easy',
    },
    'lc:590': {
      id: 'lc:590',
      number: '590',
      slug: 'n-ary-tree-postorder-traversal',
      title: 'N-ary Tree Postorder Traversal',
      difficulty: 'easy',
    },
    'lc:429': {
      id: 'lc:429',
      number: '429',
      slug: 'n-ary-tree-level-order-traversal',
      title: 'N-ary Tree Level Order Traversal',
      difficulty: 'medium',
    },
    'lc:104': {
      id: 'lc:104',
      number: '104',
      slug: 'maximum-depth-of-binary-tree',
      title: 'Maximum Depth of Binary Tree',
      difficulty: 'easy',
    },
    'lc:111': {
      id: 'lc:111',
      number: '111',
      slug: 'minimum-depth-of-binary-tree',
      title: 'Minimum Depth of Binary Tree',
      difficulty: 'easy',
    },
    'lc:543': {
      id: 'lc:543',
      number: '543',
      slug: 'diameter-of-binary-tree',
      title: 'Diameter of Binary Tree',
      difficulty: 'easy',
    },
    'lc:222': {
      id: 'lc:222',
      number: '222',
      slug: 'count-complete-tree-nodes',
      title: 'Count Complete Tree Nodes',
      difficulty: 'easy',
    },
    'lc:257': {
      id: 'lc:257',
      number: '257',
      slug: 'binary-tree-paths',
      title: 'Binary Tree Paths',
      difficulty: 'easy',
    },
    'lc:129': {
      id: 'lc:129',
      number: '129',
      slug: 'sum-root-to-leaf-numbers',
      title: 'Sum Root to Leaf Numbers',
      difficulty: 'medium',
    },
    'lc:199': {
      id: 'lc:199',
      number: '199',
      slug: 'binary-tree-right-side-view',
      title: 'Binary Tree Right Side View',
      difficulty: 'medium',
    },
    'lc:1022': {
      id: 'lc:1022',
      number: '1022',
      slug: 'sum-of-root-to-leaf-binary-numbers',
      title: 'Sum of Root To Leaf Binary Numbers',
      difficulty: 'easy',
    },
    'lc:1457': {
      id: 'lc:1457',
      number: '1457',
      slug: 'pseudo-palindromic-paths-in-a-binary-tree',
      title: 'Pseudo-Palindromic Paths in a Binary Tree',
      difficulty: 'medium',
    },
    'lc:105': {
      id: 'lc:105',
      number: '105',
      slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
      title: 'Construct Binary Tree from Preorder and Inorder Traversal',
      difficulty: 'medium',
    },
    'lc:106': {
      id: 'lc:106',
      number: '106',
      slug: 'construct-binary-tree-from-inorder-and-postorder-traversal',
      title: 'Construct Binary Tree from Inorder and Postorder Traversal',
      difficulty: 'medium',
    },
    'lc:889': {
      id: 'lc:889',
      number: '889',
      slug: 'construct-binary-tree-from-preorder-and-postorder-traversal',
      title: 'Construct Binary Tree from Preorder and Postorder Traversal',
      difficulty: 'medium',
    },
    'lc:894': {
      id: 'lc:894',
      number: '894',
      slug: 'all-possible-full-binary-trees',
      title: 'All Possible Full Binary Trees',
      difficulty: 'medium',
    },
    'lc:1110': {
      id: 'lc:1110',
      number: '1110',
      slug: 'delete-nodes-and-return-forest',
      title: 'Delete Nodes And Return Forest',
      difficulty: 'medium',
    },
    'lc:226': {
      id: 'lc:226',
      number: '226',
      slug: 'invert-binary-tree',
      title: 'Invert Binary Tree',
      difficulty: 'easy',
    },
    'lc:116': {
      id: 'lc:116',
      number: '116',
      slug: 'populating-next-right-pointers-in-each-node',
      title: 'Populating Next Right Pointers in Each Node',
      difficulty: 'medium',
    },
    'lc:114': {
      id: 'lc:114',
      number: '114',
      slug: 'flatten-binary-tree-to-linked-list',
      title: 'Flatten Binary Tree to Linked List',
      difficulty: 'medium',
    },
    'lc:654': {
      id: 'lc:654',
      number: '654',
      slug: 'maximum-binary-tree',
      title: 'Maximum Binary Tree',
      difficulty: 'medium',
    },
    'lc:297': {
      id: 'lc:297',
      number: '297',
      slug: 'serialize-and-deserialize-binary-tree',
      title: 'Serialize and Deserialize Binary Tree',
      difficulty: 'hard',
    },
    'lc:236': {
      id: 'lc:236',
      number: '236',
      slug: 'lowest-common-ancestor-of-a-binary-tree',
      title: 'Lowest Common Ancestor of a Binary Tree',
      difficulty: 'medium',
    },
    'lc:1676': {
      id: 'lc:1676',
      number: '1676',
      slug: 'lowest-common-ancestor-of-a-binary-tree-iv',
      title: 'Lowest Common Ancestor of a Binary Tree IV',
      difficulty: 'medium',
    },
    'lc:1644': {
      id: 'lc:1644',
      number: '1644',
      slug: 'lowest-common-ancestor-of-a-binary-tree-ii',
      title: 'Lowest Common Ancestor of a Binary Tree II',
      difficulty: 'medium',
    },
    'lc:235': {
      id: 'lc:235',
      number: '235',
      slug: 'lowest-common-ancestor-of-a-binary-search-tree',
      title: 'Lowest Common Ancestor of a Binary Search Tree',
      difficulty: 'medium',
    },
    'lc:1650': {
      id: 'lc:1650',
      number: '1650',
      slug: 'lowest-common-ancestor-of-a-binary-tree-iii',
      title: 'Lowest Common Ancestor of a Binary Tree III',
      difficulty: 'medium',
    },
    'lc:107': {
      id: 'lc:107',
      number: '107',
      slug: 'binary-tree-level-order-traversal-ii',
      title: 'Binary Tree Level Order Traversal II',
      difficulty: 'medium',
    },
    'lc:103': {
      id: 'lc:103',
      number: '103',
      slug: 'binary-tree-zigzag-level-order-traversal',
      title: 'Binary Tree Zigzag Level Order Traversal',
      difficulty: 'medium',
    },
    'lc:117': {
      id: 'lc:117',
      number: '117',
      slug: 'populating-next-right-pointers-in-each-node-ii',
      title: 'Populating Next Right Pointers in Each Node II',
      difficulty: 'medium',
    },
    'lc:662': {
      id: 'lc:662',
      number: '662',
      slug: 'maximum-width-of-binary-tree',
      title: 'Maximum Width of Binary Tree',
      difficulty: 'medium',
    },
    'lc:958': {
      id: 'lc:958',
      number: '958',
      slug: 'check-completeness-of-a-binary-tree',
      title: 'Check Completeness of a Binary Tree',
      difficulty: 'medium',
    },
    'lc:172': {
      id: 'lc:172',
      number: '172',
      slug: 'factorial-trailing-zeroes',
      title: 'Factorial Trailing Zeroes',
      difficulty: 'medium',
    },
    'lc:793': {
      id: 'lc:793',
      number: '793',
      slug: 'preimage-size-of-factorial-zeroes-function',
      title: 'Preimage Size of Factorial Zeroes Function',
      difficulty: 'hard',
    },
    'lc:204': {
      id: 'lc:204',
      number: '204',
      slug: 'count-primes',
      title: 'Count Primes',
      difficulty: 'medium',
    },
    'lc:372': {
      id: 'lc:372',
      number: '372',
      slug: 'super-pow',
      title: 'Super Pow',
      difficulty: 'medium',
    },
    'lc:292': {
      id: 'lc:292',
      number: '292',
      slug: 'nim-game',
      title: 'Nim Game',
      difficulty: 'easy',
    },
    'lc:877': {
      id: 'lc:877',
      number: '877',
      slug: 'stone-game',
      title: 'Stone Game',
      difficulty: 'medium',
    },
    'lc:319': {
      id: 'lc:319',
      number: '319',
      slug: 'bulb-switcher',
      title: 'Bulb Switcher',
      difficulty: 'medium',
    },
    'lc:263': {
      id: 'lc:263',
      number: '263',
      slug: 'ugly-number',
      title: 'Ugly Number',
      difficulty: 'easy',
    },
    'lc:264': {
      id: 'lc:264',
      number: '264',
      slug: 'ugly-number-ii',
      title: 'Ugly Number II',
      difficulty: 'medium',
    },
    'lc:313': {
      id: 'lc:313',
      number: '313',
      slug: 'super-ugly-number',
      title: 'Super Ugly Number',
      difficulty: 'medium',
    },
    'lc:1201': {
      id: 'lc:1201',
      number: '1201',
      slug: 'ugly-number-iii',
      title: 'Ugly Number III',
      difficulty: 'medium',
    },
    'lc:55': {
      id: 'lc:55',
      number: '55',
      slug: 'jump-game',
      title: 'Jump Game',
      difficulty: 'medium',
    },
    'lc:45': {
      id: 'lc:45',
      number: '45',
      slug: 'jump-game-ii',
      title: 'Jump Game II',
      difficulty: 'medium',
    },
    'lc:134': {
      id: 'lc:134',
      number: '134',
      slug: 'gas-station',
      title: 'Gas Station',
      difficulty: 'medium',
    },
    'lc:435': {
      id: 'lc:435',
      number: '435',
      slug: 'non-overlapping-intervals',
      title: 'Non-overlapping Intervals',
      difficulty: 'medium',
    },
    'lc:452': {
      id: 'lc:452',
      number: '452',
      slug: 'minimum-number-of-arrows-to-burst-balloons',
      title: 'Minimum Number of Arrows to Burst Balloons',
      difficulty: 'medium',
    },
    'lc:253': {
      id: 'lc:253',
      number: '253',
      slug: 'meeting-rooms-ii',
      title: 'Meeting Rooms II',
      difficulty: 'medium',
    },
    'lc:1235': {
      id: 'lc:1235',
      number: '1235',
      slug: 'maximum-profit-in-job-scheduling',
      title: 'Maximum Profit in Job Scheduling',
      difficulty: 'hard',
    },
    'lc:200': {
      id: 'lc:200',
      number: '200',
      slug: 'number-of-islands',
      title: 'Number of Islands',
      difficulty: 'medium',
    },
    'lc:1254': {
      id: 'lc:1254',
      number: '1254',
      slug: 'number-of-closed-islands',
      title: 'Number of Closed Islands',
      difficulty: 'medium',
    },
    'lc:1020': {
      id: 'lc:1020',
      number: '1020',
      slug: 'number-of-enclaves',
      title: 'Number of Enclaves',
      difficulty: 'medium',
    },
    'lc:695': {
      id: 'lc:695',
      number: '695',
      slug: 'max-area-of-island',
      title: 'Max Area of Island',
      difficulty: 'medium',
    },
    'lc:1905': {
      id: 'lc:1905',
      number: '1905',
      slug: 'count-sub-islands',
      title: 'Count Sub Islands',
      difficulty: 'medium',
    },
    'lc:694': {
      id: 'lc:694',
      number: '694',
      slug: 'number-of-distinct-islands',
      title: 'Number of Distinct Islands',
      difficulty: 'medium',
    },
    'lc:967': {
      id: 'lc:967',
      number: '967',
      slug: 'numbers-with-same-consecutive-differences',
      title: 'Numbers With Same Consecutive Differences',
      difficulty: 'medium',
    },
    'lc:491': {
      id: 'lc:491',
      number: '491',
      slug: 'non-decreasing-subsequences',
      title: 'Non-decreasing Subsequences',
      difficulty: 'medium',
    },
    'lc:980': {
      id: 'lc:980',
      number: '980',
      slug: 'unique-paths-iii',
      title: 'Unique Paths III',
      difficulty: 'hard',
    },
    'lc:131': {
      id: 'lc:131',
      number: '131',
      slug: 'palindrome-partitioning',
      title: 'Palindrome Partitioning',
      difficulty: 'medium',
    },
    'lc:93': {
      id: 'lc:93',
      number: '93',
      slug: 'restore-ip-addresses',
      title: 'Restore IP Addresses',
      difficulty: 'medium',
    },
    'lc:17': {
      id: 'lc:17',
      number: '17',
      slug: 'letter-combinations-of-a-phone-number',
      title: 'Letter Combinations of a Phone Number',
      difficulty: 'medium',
    },
    'lc:79': {
      id: 'lc:79',
      number: '79',
      slug: 'word-search',
      title: 'Word Search',
      difficulty: 'medium',
    },
    'lc:46': {
      id: 'lc:46',
      number: '46',
      slug: 'permutations',
      title: 'Permutations',
      difficulty: 'medium',
    },
    'lc:37': {
      id: 'lc:37',
      number: '37',
      slug: 'sudoku-solver',
      title: 'Sudoku Solver',
      difficulty: 'hard',
    },
    'lc:51': {
      id: 'lc:51',
      number: '51',
      slug: 'n-queens',
      title: 'N-Queens',
      difficulty: 'hard',
    },
    'lc:52': {
      id: 'lc:52',
      number: '52',
      slug: 'n-queens-ii',
      title: 'N-Queens II',
      difficulty: 'hard',
    },
    'lc:78': {
      id: 'lc:78',
      number: '78',
      slug: 'subsets',
      title: 'Subsets',
      difficulty: 'medium',
    },
    'lc:77': {
      id: 'lc:77',
      number: '77',
      slug: 'combinations',
      title: 'Combinations',
      difficulty: 'medium',
    },
    'lc:90': {
      id: 'lc:90',
      number: '90',
      slug: 'subsets-ii',
      title: 'Subsets II',
      difficulty: 'medium',
    },
    'lc:40': {
      id: 'lc:40',
      number: '40',
      slug: 'combination-sum-ii',
      title: 'Combination Sum II',
      difficulty: 'medium',
    },
    'lc:47': {
      id: 'lc:47',
      number: '47',
      slug: 'permutations-ii',
      title: 'Permutations II',
      difficulty: 'medium',
    },
    'lc:39': {
      id: 'lc:39',
      number: '39',
      slug: 'combination-sum',
      title: 'Combination Sum',
      difficulty: 'medium',
    },
    'lc:216': {
      id: 'lc:216',
      number: '216',
      slug: 'combination-sum-iii',
      title: 'Combination Sum III',
      difficulty: 'medium',
    },
    'lc:322': {
      id: 'lc:322',
      number: '322',
      slug: 'coin-change',
      title: 'Coin Change',
      difficulty: 'medium',
    },
    'lc:300': {
      id: 'lc:300',
      number: '300',
      slug: 'longest-increasing-subsequence',
      title: 'Longest Increasing Subsequence',
      difficulty: 'medium',
    },
    'lc:354': {
      id: 'lc:354',
      number: '354',
      slug: 'russian-doll-envelopes',
      title: 'Russian Doll Envelopes',
      difficulty: 'hard',
    },
    'lc:518': {
      id: 'lc:518',
      number: '518',
      slug: 'coin-change-ii',
      title: 'Coin Change II',
      difficulty: 'medium',
    },
    'lc:494': {
      id: 'lc:494',
      number: '494',
      slug: 'target-sum',
      title: 'Target Sum',
      difficulty: 'medium',
    },
    'lc:198': {
      id: 'lc:198',
      number: '198',
      slug: 'house-robber',
      title: 'House Robber',
      difficulty: 'medium',
    },
    'lc:213': {
      id: 'lc:213',
      number: '213',
      slug: 'house-robber-ii',
      title: 'House Robber II',
      difficulty: 'medium',
    },
    'lc:337': {
      id: 'lc:337',
      number: '337',
      slug: 'house-robber-iii',
      title: 'House Robber III',
      difficulty: 'medium',
    },
    'lc:72': {
      id: 'lc:72',
      number: '72',
      slug: 'edit-distance',
      title: 'Edit Distance',
      difficulty: 'medium',
    },
    'lc:53': {
      id: 'lc:53',
      number: '53',
      slug: 'maximum-subarray',
      title: 'Maximum Subarray',
      difficulty: 'medium',
    },
    'lc:1143': {
      id: 'lc:1143',
      number: '1143',
      slug: 'longest-common-subsequence',
      title: 'Longest Common Subsequence',
      difficulty: 'medium',
    },
    'lc:583': {
      id: 'lc:583',
      number: '583',
      slug: 'delete-operation-for-two-strings',
      title: 'Delete Operation for Two Strings',
      difficulty: 'medium',
    },
    'lc:712': {
      id: 'lc:712',
      number: '712',
      slug: 'minimum-ascii-delete-sum-for-two-strings',
      title: 'Minimum ASCII Delete Sum for Two Strings',
      difficulty: 'medium',
    },
    'lc:516': {
      id: 'lc:516',
      number: '516',
      slug: 'longest-palindromic-subsequence',
      title: 'Longest Palindromic Subsequence',
      difficulty: 'medium',
    },
    'lc:1312': {
      id: 'lc:1312',
      number: '1312',
      slug: 'minimum-insertion-steps-to-make-a-string-palindrome',
      title: 'Minimum Insertion Steps to Make a String Palindrome',
      difficulty: 'hard',
    },
    'lc:509': {
      id: 'lc:509',
      number: '509',
      slug: 'fibonacci-number',
      title: 'Fibonacci Number',
      difficulty: 'easy',
    },
    'lc:931': {
      id: 'lc:931',
      number: '931',
      slug: 'minimum-falling-path-sum',
      title: 'Minimum Falling Path Sum',
      difficulty: 'medium',
    },
    'lc:416': {
      id: 'lc:416',
      number: '416',
      slug: 'partition-equal-subset-sum',
      title: 'Partition Equal Subset Sum',
      difficulty: 'medium',
    },
    'lc:863': {
      id: 'lc:863',
      number: '863',
      slug: 'all-nodes-distance-k-in-binary-tree',
      title: 'All Nodes Distance K in Binary Tree',
      difficulty: 'medium',
    },
    'lc:310': {
      id: 'lc:310',
      number: '310',
      slug: 'minimum-height-trees',
      title: 'Minimum Height Trees',
      difficulty: 'medium',
    },
    'lc:841': {
      id: 'lc:841',
      number: '841',
      slug: 'keys-and-rooms',
      title: 'Keys and Rooms',
      difficulty: 'medium',
    },
    'lc:1926': {
      id: 'lc:1926',
      number: '1926',
      slug: 'nearest-exit-from-entrance-in-maze',
      title: 'Nearest Exit from Entrance in Maze',
      difficulty: 'medium',
    },
    'lc:1091': {
      id: 'lc:1091',
      number: '1091',
      slug: 'shortest-path-in-binary-matrix',
      title: 'Shortest Path in Binary Matrix',
      difficulty: 'medium',
    },
    'lc:752': {
      id: 'lc:752',
      number: '752',
      slug: 'open-the-lock',
      title: 'Open the Lock',
      difficulty: 'medium',
    },
    'lc:773': {
      id: 'lc:773',
      number: '773',
      slug: 'sliding-puzzle',
      title: 'Sliding Puzzle',
      difficulty: 'hard',
    },
    'lc:743': {
      id: 'lc:743',
      number: '743',
      slug: 'network-delay-time',
      title: 'Network Delay Time',
      difficulty: 'medium',
    },
    'lc:1631': {
      id: 'lc:1631',
      number: '1631',
      slug: 'path-with-minimum-effort',
      title: 'Path With Minimum Effort',
      difficulty: 'medium',
    },
    'lc:1514': {
      id: 'lc:1514',
      number: '1514',
      slug: 'path-with-maximum-probability',
      title: 'Path with Maximum Probability',
      difficulty: 'medium',
    },
    'lc:1368': {
      id: 'lc:1368',
      number: '1368',
      slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid',
      title: 'Minimum Cost to Make at Least One Valid Path in a Grid',
      difficulty: 'hard',
    },
    'lc:787': {
      id: 'lc:787',
      number: '787',
      slug: 'cheapest-flights-within-k-stops',
      title: 'Cheapest Flights Within K Stops',
      difficulty: 'medium',
    },
    'lc:700': {
      id: 'lc:700',
      number: '700',
      slug: 'search-in-a-binary-search-tree',
      title: 'Search in a Binary Search Tree',
      difficulty: 'easy',
    },
    'lc:701': {
      id: 'lc:701',
      number: '701',
      slug: 'insert-into-a-binary-search-tree',
      title: 'Insert into a Binary Search Tree',
      difficulty: 'medium',
    },
    'lc:450': {
      id: 'lc:450',
      number: '450',
      slug: 'delete-node-in-a-bst',
      title: 'Delete Node in a BST',
      difficulty: 'medium',
    },
    'lc:98': {
      id: 'lc:98',
      number: '98',
      slug: 'validate-binary-search-tree',
      title: 'Validate Binary Search Tree',
      difficulty: 'medium',
    },
    'lc:230': {
      id: 'lc:230',
      number: '230',
      slug: 'kth-smallest-element-in-a-bst',
      title: 'Kth Smallest Element in a BST',
      difficulty: 'medium',
    },
    'lc:538': {
      id: 'lc:538',
      number: '538',
      slug: 'convert-bst-to-greater-tree',
      title: 'Convert BST to Greater Tree',
      difficulty: 'medium',
    },
    'lc:1038': {
      id: 'lc:1038',
      number: '1038',
      slug: 'binary-search-tree-to-greater-sum-tree',
      title: 'Binary Search Tree to Greater Sum Tree',
      difficulty: 'medium',
    },
    'lc:96': {
      id: 'lc:96',
      number: '96',
      slug: 'unique-binary-search-trees',
      title: 'Unique Binary Search Trees',
      difficulty: 'medium',
    },
    'lc:95': {
      id: 'lc:95',
      number: '95',
      slug: 'unique-binary-search-trees-ii',
      title: 'Unique Binary Search Trees II',
      difficulty: 'medium',
    },
    'lc:1373': {
      id: 'lc:1373',
      number: '1373',
      slug: 'maximum-sum-bst-in-binary-tree',
      title: 'Maximum Sum BST in Binary Tree',
      difficulty: 'hard',
    },
    'lc:355': {
      id: 'lc:355',
      number: '355',
      slug: 'design-twitter',
      title: 'Design Twitter',
      difficulty: 'medium',
    },
    'lc:215': {
      id: 'lc:215',
      number: '215',
      slug: 'kth-largest-element-in-an-array',
      title: 'Kth Largest Element in an Array',
      difficulty: 'medium',
    },
    'lc:703': {
      id: 'lc:703',
      number: '703',
      slug: 'kth-largest-element-in-a-stream',
      title: 'Kth Largest Element in a Stream',
      difficulty: 'easy',
    },
    'lc:347': {
      id: 'lc:347',
      number: '347',
      slug: 'top-k-frequent-elements',
      title: 'Top K Frequent Elements',
      difficulty: 'medium',
    },
    'lc:295': {
      id: 'lc:295',
      number: '295',
      slug: 'find-median-from-data-stream',
      title: 'Find Median from Data Stream',
      difficulty: 'hard',
    },
    'lc:208': {
      id: 'lc:208',
      number: '208',
      slug: 'implement-trie-prefix-tree',
      title: 'Implement Trie (Prefix Tree)',
      difficulty: 'medium',
    },
    'lc:1804': {
      id: 'lc:1804',
      number: '1804',
      slug: 'implement-trie-ii-prefix-tree',
      title: 'Implement Trie II (Prefix Tree)',
      difficulty: 'medium',
    },
    'lc:648': {
      id: 'lc:648',
      number: '648',
      slug: 'replace-words',
      title: 'Replace Words',
      difficulty: 'medium',
    },
    'lc:211': {
      id: 'lc:211',
      number: '211',
      slug: 'design-add-and-search-words-data-structure',
      title: 'Design Add and Search Words Data Structure',
      difficulty: 'medium',
    },
    'lc:677': {
      id: 'lc:677',
      number: '677',
      slug: 'map-sum-pairs',
      title: 'Map Sum Pairs',
      difficulty: 'medium',
    },
    'lc:785': {
      id: 'lc:785',
      number: '785',
      slug: 'is-graph-bipartite',
      title: 'Is Graph Bipartite?',
      difficulty: 'medium',
    },
    'lc:886': {
      id: 'lc:886',
      number: '886',
      slug: 'possible-bipartition',
      title: 'Possible Bipartition',
      difficulty: 'medium',
    },
    'lc:207': {
      id: 'lc:207',
      number: '207',
      slug: 'course-schedule',
      title: 'Course Schedule',
      difficulty: 'medium',
    },
    'lc:210': {
      id: 'lc:210',
      number: '210',
      slug: 'course-schedule-ii',
      title: 'Course Schedule II',
      difficulty: 'medium',
    },
    'lc:323': {
      id: 'lc:323',
      number: '323',
      slug: 'number-of-connected-components-in-an-undirected-graph',
      title: 'Number of Connected Components in an Undirected Graph',
      difficulty: 'medium',
    },
    'lc:130': {
      id: 'lc:130',
      number: '130',
      slug: 'surrounded-regions',
      title: 'Surrounded Regions',
      difficulty: 'medium',
    },
    'lc:990': {
      id: 'lc:990',
      number: '990',
      slug: 'satisfiability-of-equality-equations',
      title: 'Satisfiability of Equality Equations',
      difficulty: 'medium',
    },
    'lc:261': {
      id: 'lc:261',
      number: '261',
      slug: 'graph-valid-tree',
      title: 'Graph Valid Tree',
      difficulty: 'medium',
    },
    'lc:1135': {
      id: 'lc:1135',
      number: '1135',
      slug: 'connecting-cities-with-minimum-cost',
      title: 'Connecting Cities With Minimum Cost',
      difficulty: 'medium',
    },
    'lc:1584': {
      id: 'lc:1584',
      number: '1584',
      slug: 'min-cost-to-connect-all-points',
      title: 'Min Cost to Connect All Points',
      difficulty: 'medium',
    },
    'lc:974': {
      id: 'lc:974',
      number: '974',
      slug: 'subarray-sums-divisible-by-k',
      title: 'Subarray Sums Divisible by K',
      difficulty: 'medium',
    },
    'lc:1670': {
      id: 'lc:1670',
      number: '1670',
      slug: 'design-front-middle-back-queue',
      title: 'Design Front Middle Back Queue',
      difficulty: 'medium',
    },
    'lc:388': {
      id: 'lc:388',
      number: '388',
      slug: 'longest-absolute-file-path',
      title: 'Longest Absolute File Path',
      difficulty: 'medium',
    },
    'lc:895': {
      id: 'lc:895',
      number: '895',
      slug: 'maximum-frequency-stack',
      title: 'Maximum Frequency Stack',
      difficulty: 'hard',
    },
    'lc:217': {
      id: 'lc:217',
      number: '217',
      slug: 'contains-duplicate',
      title: 'Contains Duplicate',
      difficulty: 'easy',
    },
    'lc:136': {
      id: 'lc:136',
      number: '136',
      slug: 'single-number',
      title: 'Single Number',
      difficulty: 'easy',
    },
    'lc:1696': {
      id: 'lc:1696',
      number: '1696',
      slug: 'jump-game-vi',
      title: 'Jump Game VI',
      difficulty: 'medium',
    },
    'lc:1425': {
      id: 'lc:1425',
      number: '1425',
      slug: 'constrained-subsequence-sum',
      title: 'Constrained Subsequence Sum',
      difficulty: 'hard',
    },
    'lc:284': {
      id: 'lc:284',
      number: '284',
      slug: 'peeking-iterator',
      title: 'Peeking Iterator',
      difficulty: 'medium',
    },
    'lc:1944': {
      id: 'lc:1944',
      number: '1944',
      slug: 'number-of-visible-people-in-a-queue',
      title: 'Number of Visible People in a Queue',
      difficulty: 'hard',
    },
    'lc:1475': {
      id: 'lc:1475',
      number: '1475',
      slug: 'final-prices-with-a-special-discount-in-a-shop',
      title: 'Final Prices With a Special Discount in a Shop',
      difficulty: 'easy',
    },
    'lc:581': {
      id: 'lc:581',
      number: '581',
      slug: 'shortest-unsorted-continuous-subarray',
      title: 'Shortest Unsorted Continuous Subarray',
      difficulty: 'medium',
    },
    'lc:519': {
      id: 'lc:519',
      number: '519',
      slug: 'random-flip-matrix',
      title: 'Random Flip Matrix',
      difficulty: 'medium',
    },
    'lc:389': {
      id: 'lc:389',
      number: '389',
      slug: 'find-the-difference',
      title: 'Find the Difference',
      difficulty: 'easy',
    },
    'lc:442': {
      id: 'lc:442',
      number: '442',
      slug: 'find-all-duplicates-in-an-array',
      title: 'Find All Duplicates in an Array',
      difficulty: 'medium',
    },
    'lc:448': {
      id: 'lc:448',
      number: '448',
      slug: 'find-all-numbers-disappeared-in-an-array',
      title: 'Find All Numbers Disappeared in an Array',
      difficulty: 'easy',
    },
    'lc:912': {
      id: 'lc:912',
      number: '912',
      slug: 'sort-an-array',
      title: 'Sort an Array',
      difficulty: 'medium',
    },
    'lc:220': {
      id: 'lc:220',
      number: '220',
      slug: 'contains-duplicate-iii',
      title: 'Contains Duplicate III',
      difficulty: 'hard',
    },
    'lc:395': {
      id: 'lc:395',
      number: '395',
      slug: 'longest-substring-with-at-least-k-repeating-characters',
      title: 'Longest Substring with At Least K Repeating Characters',
      difficulty: 'medium',
    },
    'lc:988': {
      id: 'lc:988',
      number: '988',
      slug: 'smallest-string-starting-from-leaf',
      title: 'Smallest String Starting From Leaf',
      difficulty: 'medium',
    },
    'lc:331': {
      id: 'lc:331',
      number: '331',
      slug: 'verify-preorder-serialization-of-a-binary-tree',
      title: 'Verify Preorder Serialization of a Binary Tree',
      difficulty: 'medium',
    },
    'lc:998': {
      id: 'lc:998',
      number: '998',
      slug: 'maximum-binary-tree-ii',
      title: 'Maximum Binary Tree II',
      difficulty: 'medium',
    },
    'lc:515': {
      id: 'lc:515',
      number: '515',
      slug: 'find-largest-value-in-each-tree-row',
      title: 'Find Largest Value in Each Tree Row',
      difficulty: 'medium',
    },
    'lc:637': {
      id: 'lc:637',
      number: '637',
      slug: 'average-of-levels-in-binary-tree',
      title: 'Average of Levels in Binary Tree',
      difficulty: 'easy',
    },
    'lc:1161': {
      id: 'lc:1161',
      number: '1161',
      slug: 'maximum-level-sum-of-a-binary-tree',
      title: 'Maximum Level Sum of a Binary Tree',
      difficulty: 'medium',
    },
    'lc:1302': {
      id: 'lc:1302',
      number: '1302',
      slug: 'deepest-leaves-sum',
      title: 'Deepest Leaves Sum',
      difficulty: 'medium',
    },
    'lc:1609': {
      id: 'lc:1609',
      number: '1609',
      slug: 'even-odd-tree',
      title: 'Even Odd Tree',
      difficulty: 'medium',
    },
    'lc:8': {
      id: 'lc:8',
      number: '8',
      slug: 'string-to-integer-atoi',
      title: 'String to Integer (atoi)',
      difficulty: 'medium',
    },
    'lc:9': {
      id: 'lc:9',
      number: '9',
      slug: 'palindrome-number',
      title: 'Palindrome Number',
      difficulty: 'easy',
    },
    'lc:50': {
      id: 'lc:50',
      number: '50',
      slug: 'powx-n',
      title: 'Pow(x, n)',
      difficulty: 'medium',
    },
    'lc:67': {
      id: 'lc:67',
      number: '67',
      slug: 'add-binary',
      title: 'Add Binary',
      difficulty: 'easy',
    },
    'lc:400': {
      id: 'lc:400',
      number: '400',
      slug: 'nth-digit',
      title: 'Nth Digit',
      difficulty: 'medium',
    },
    'lc:306': {
      id: 'lc:306',
      number: '306',
      slug: 'additive-number',
      title: 'Additive Number',
      difficulty: 'medium',
    },
    'lc:842': {
      id: 'lc:842',
      number: '842',
      slug: 'split-array-into-fibonacci-sequence',
      title: 'Split Array into Fibonacci Sequence',
      difficulty: 'medium',
    },
    'lc:357': {
      id: 'lc:357',
      number: '357',
      slug: 'count-numbers-with-unique-digits',
      title: 'Count Numbers with Unique Digits',
      difficulty: 'medium',
    },
    'lc:279': {
      id: 'lc:279',
      number: '279',
      slug: 'perfect-squares',
      title: 'Perfect Squares',
      difficulty: 'medium',
    },
    'lc:526': {
      id: 'lc:526',
      number: '526',
      slug: 'beautiful-arrangement',
      title: 'Beautiful Arrangement',
      difficulty: 'medium',
    },
    'lc:89': {
      id: 'lc:89',
      number: '89',
      slug: 'gray-code',
      title: 'Gray Code',
      difficulty: 'medium',
    },
    'lc:473': {
      id: 'lc:473',
      number: '473',
      slug: 'matchsticks-to-square',
      title: 'Matchsticks to Square',
      difficulty: 'medium',
    },
    'lc:919': {
      id: 'lc:919',
      number: '919',
      slug: 'complete-binary-tree-inserter',
      title: 'Complete Binary Tree Inserter',
      difficulty: 'medium',
    },
    'lc:1306': {
      id: 'lc:1306',
      number: '1306',
      slug: 'jump-game-iii',
      title: 'Jump Game III',
      difficulty: 'medium',
    },
    'lc:433': {
      id: 'lc:433',
      number: '433',
      slug: 'minimum-genetic-mutation',
      title: 'Minimum Genetic Mutation',
      difficulty: 'medium',
    },
    'lc:872': {
      id: 'lc:872',
      number: '872',
      slug: 'leaf-similar-trees',
      title: 'Leaf-Similar Trees',
      difficulty: 'easy',
    },
    'lc:451': {
      id: 'lc:451',
      number: '451',
      slug: 'sort-characters-by-frequency',
      title: 'Sort Characters By Frequency',
      difficulty: 'medium',
    },
    'lc:692': {
      id: 'lc:692',
      number: '692',
      slug: 'top-k-frequent-words',
      title: 'Top K Frequent Words',
      difficulty: 'medium',
    },
    'lc:1845': {
      id: 'lc:1845',
      number: '1845',
      slug: 'seat-reservation-manager',
      title: 'Seat Reservation Manager',
      difficulty: 'medium',
    },
    'lc:870': {
      id: 'lc:870',
      number: '870',
      slug: 'advantage-shuffle',
      title: 'Advantage Shuffle',
      difficulty: 'medium',
    },
    'lc:1834': {
      id: 'lc:1834',
      number: '1834',
      slug: 'single-threaded-cpu',
      title: 'Single-Threaded CPU',
      difficulty: 'medium',
    },
    'lc:547': {
      id: 'lc:547',
      number: '547',
      slug: 'number-of-provinces',
      title: 'Number of Provinces',
      difficulty: 'medium',
    },
    'lc:1361': {
      id: 'lc:1361',
      number: '1361',
      slug: 'validate-binary-tree-nodes',
      title: 'Validate Binary Tree Nodes',
      difficulty: 'medium',
    },
    'lc:947': {
      id: 'lc:947',
      number: '947',
      slug: 'most-stones-removed-with-same-row-or-column',
      title: 'Most Stones Removed with Same Row or Column',
      difficulty: 'medium',
    },

  },
}
