import type { AlgorithmKnowledgeData, AlgorithmProblemTag, Difficulty, Relation } from '@/types'

export const ALGORITHM_DIFFICULTY_COLORS: Record<Difficulty, string> = {
  easy: 'rgba(94, 234, 212, 0.78)',
  medium: 'rgba(251, 146, 120, 0.78)',
  hard: 'rgba(251, 113, 133, 0.78)',
}

export const ALGORITHM_GROUP_NODE_COLOR = 'rgba(96, 165, 250, 0.82)'
export const ALGORITHM_TOPIC_NODE_COLOR = 'rgba(228, 228, 231, 0.82)'

export function getAlgorithmDifficultyColor(difficulty?: Difficulty): string {
  if (!difficulty)
    return 'var(--muted)'
  return ALGORITHM_DIFFICULTY_COLORS[difficulty] ?? 'var(--muted)'
}

const CHECKIN_TOPIC_SEQUENCE: Array<{ id: string, title: string }> = [
  {
    id: 'two-pointer-linked',
    title: '链表双指针',
  },
  {
    id: 'prefix-sum',
    title: '前缀和',
  },
  {
    id: 'diff-array',
    title: '差分数组',
  },
  {
    id: '2d-array-ops',
    title: '二维数组',
  },
  {
    id: 'array-ops',
    title: '数组技巧',
  },
  {
    id: 'interval',
    title: '区间',
  },
  {
    id: 'string-ops',
    title: '字符串',
  },
  {
    id: 'cycle-array',
    title: '循环数组',
  },
  {
    id: 'stack',
    title: '栈',
  },
  {
    id: 'queue',
    title: '队列',
  },
  {
    id: 'monotonic-stack',
    title: '单调栈',
  },
  {
    id: 'monotonic-queue',
    title: '单调队列',
  },
  {
    id: 'hashing',
    title: '哈希',
  },
  {
    id: 'design',
    title: '设计',
  },
  {
    id: 'two-pointer-array',
    title: '数组双指针',
  },
  {
    id: 'sliding-window',
    title: '滑动窗口',
  },
  {
    id: 'binary-search',
    title: '二分搜索',
  },
  {
    id: 'random',
    title: '随机算法',
  },
  {
    id: 'recursion-ops',
    title: '递归',
  },
  {
    id: 'binary-tree',
    title: '二叉树',
  },
  {
    id: 'recursive-traverse',
    title: '递归遍历',
  },
  {
    id: 'level-order-traverse',
    title: '层序遍历',
  },
  {
    id: 'bst',
    title: '二叉搜索树',
  },
  {
    id: 'heap',
    title: '堆',
  },
  {
    id: 'trie',
    title: '字典树',
  },
  {
    id: 'backtracking',
    title: '回溯算法',
  },
  {
    id: 'dfs',
    title: '深度优先搜索',
  },
  {
    id: 'dp',
    title: '动态规划',
  },
  {
    id: 'divide-conquer',
    title: '分治算法',
  },
  {
    id: 'greedy',
    title: '贪心算法',
  },
  {
    id: 'bfs',
    title: '广度优先搜索',
  },
  {
    id: 'graph',
    title: '图',
  },
  {
    id: 'shortest-path',
    title: '最短路径',
  },
  {
    id: 'math',
    title: '数学',
  },
  {
    id: 'bitwise',
    title: '位运算',
  },
]

const CHECKIN_TOPIC_ORDER = new Map<string, number>(
  CHECKIN_TOPIC_SEQUENCE.map((topic, index) => [topic.id, index]),
)

const CHECKIN_TOPIC_TITLE = CHECKIN_TOPIC_SEQUENCE.reduce<Record<string, string>>(
  (acc, topic) => {
    acc[topic.id] = topic.title
    return acc
  },
  {},
)

const KNOWLEDGE_GROUPS: AlgorithmKnowledgeData['groups'] = [
  {
    id: 'array-operation-group',
    title: '数组操作',
  },
  {
    id: 'basic-ds-group',
    title: '基础数据结构',
  },
  {
    id: 'two-pointer-group',
    title: '双指针技巧',
  },
  {
    id: 'other-group',
    title: '其他算法',
  },
  {
    id: 'traverse-view-group',
    title: '遍历视角',
  },
  {
    id: 'subproblem-view-group',
    title: '子问题视角',
  },
  {
    id: 'advanced-ds-group',
    title: '高级数据结构',
  },
]

export const ALGORITHM_RELATIONS: Relation[] = [
  { source: 'array-operation-group', target: 'two-pointer-group' },
  { source: 'array-operation-group', target: 'basic-ds-group' },
  { source: 'two-pointer-linked', target: 'recursion-ops' },
  { source: 'recursion-ops', target: 'binary-tree' },
  { source: 'binary-tree', target: 'recursive-traverse' },
  { source: 'binary-tree', target: 'level-order-traverse' },
  { source: 'binary-tree', target: 'advanced-ds-group' },
  { source: 'recursive-traverse', target: 'traverse-view-group' },
  { source: 'recursive-traverse', target: 'subproblem-view-group' },
  { source: 'level-order-traverse', target: 'bfs' },
  { source: 'bfs', target: 'shortest-path' },
]

export const ALGORITHM_PROBLEM_TAG_LABELS: Record<AlgorithmProblemTag, string> = {
  hot100: 'hot100',
  interview150: 'interview150',
}

export const ALGORITHM_STUDY_PLAN_TITLES: Record<AlgorithmProblemTag, string> = {
  hot100: 'Hot 100',
  interview150: 'Interview 150',
}

export const ALGORITHM_PROBLEM_TAG_ORDER: AlgorithmProblemTag[] = ['hot100', 'interview150']

export const ALGORITHM_PROBLEM_TAG_ICONS: Record<AlgorithmProblemTag, string> = {
  hot100: 'i-ri:fire-fill text-red-500/90',
  interview150: 'i-ri:trophy-fill text-amber-500/90',
}

const KNOWLEDGE_TOPICS_RAW: AlgorithmKnowledgeData['topics'] = [
  {
    id: 'diff-array',
    title: '差分数组',
    groupId: 'array-operation-group',
    difficulty: 'easy',
    problemIds: [
      'lc:370',
      'lc:1094',
      'lc:1109',
    ],
  },
  {
    id: '2d-array-ops',
    title: '二维数组',
    groupId: 'array-operation-group',
    difficulty: 'easy',
    problemIds: [
      'lc:36',
      'lc:48',
      'lc:54',
      'lc:59',
      'lc:61',
      'lc:73',
      'lc:151',
      'lc:289',
      'lc:lcr-146',
    ],
  },
  {
    id: 'array-ops',
    title: '数组技巧',
    groupId: 'array-operation-group',
    difficulty: 'medium',
    problemIds: [
      'lc:31',
      'lc:41',
      'lc:189',
      'lc:274',
    ],
  },
  {
    id: 'interval',
    title: '区间',
    groupId: 'array-operation-group',
    difficulty: 'medium',
    problemIds: [
      'lc:56',
      'lc:57',
      'lc:228',
    ],
  },
  {
    id: 'string-ops',
    title: '字符串',
    groupId: 'array-operation-group',
    difficulty: 'medium',
    problemIds: [
      'lc:6',
      'lc:28',
      'lc:58',
      'lc:68',
    ],
  },
  {
    id: 'prefix-sum',
    title: '前缀和',
    groupId: 'array-operation-group',
    difficulty: 'easy',
    problemIds: [
      'lc:238',
      'lc:303',
      'lc:304',
      'lc:523',
      'lc:525',
      'lc:560',
      'lc:724',
      'lc:974',
      'lc:1124',
      'lc:1314',
      'lc:1352',
    ],
  },
  {
    id: 'cycle-array',
    title: '循环数组',
    groupId: 'basic-ds-group',
    difficulty: 'easy',
    problemIds: [
      'lc:622',
      'lc:641',
    ],
  },
  {
    id: 'stack',
    title: '栈',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:20',
      'lc:32',
      'lc:71',
      'lc:143',
      'lc:150',
      'lc:155',
      'lc:394',
      'lc:225',
      'lc:388',
      'lc:895',
    ],
  },
  {
    id: 'queue',
    title: '队列',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:232',
      'lc:622',
      'lc:641',
      'lc:933',
      'lc:1670',
      'lc:2073',
    ],
  },
  {
    id: 'monotonic-stack',
    title: '单调栈',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:402',
      'lc:496',
      'lc:503',
      'lc:581',
      'lc:84',
      'lc:739',
      'lc:853',
      'lc:901',
      'lc:1019',
      'lc:1475',
      'lc:1944',
      'lc:lcr-038',
    ],
  },
  {
    id: 'monotonic-queue',
    title: '单调队列',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:239',
      'lc:862',
      'lc:918',
      'lc:1425',
      'lc:1438',
      'lc:1696',
      'lc:lcr-184',
    ],
  },
  {
    id: 'hashing',
    title: '哈希',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:1',
      'lc:49',
      'lc:128',
      'lc:133',
      'lc:136',
      'lc:138',
      'lc:169',
      'lc:217',
      'lc:242',
      'lc:290',
      'lc:387',
      'lc:389',
      'lc:442',
      'lc:448',
      'lc:519',
      'lc:205',
      'lc:383',
    ],
  },
  {
    id: 'design',
    title: '设计',
    groupId: 'basic-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:146',
      'lc:155',
      'lc:224',
      'lc:227',
      'lc:284',
      'lc:729',
      'lc:772',
      'lc:895',
      'lc:950',
      'lc:1670',
      'lc:1700',
      'lc:380',
    ],
  },
  {
    id: 'two-pointer-array',
    title: '数组双指针',
    groupId: 'two-pointer-group',
    difficulty: 'easy',
    problemIds: [
      'lc:1',
      'lc:5',
      'lc:11',
      'lc:14',
      'lc:15',
      'lc:18',
      'lc:26',
      'lc:27',
      'lc:42',
      'lc:75',
      'lc:80',
      'lc:83',
      'lc:88',
      'lc:125',
      'lc:167',
      'lc:283',
      'lc:344',
      'lc:867',
      'lc:977',
      'lc:1260',
      'lc:1329',
    ],
  },
  {
    id: 'sliding-window',
    title: '滑动窗口',
    groupId: 'two-pointer-group',
    difficulty: 'medium',
    problemIds: [
      'lc:3',
      'lc:76',
      'lc:209',
      'lc:219',
      'lc:220',
      'lc:395',
      'lc:424',
      'lc:438',
      'lc:567',
      'lc:713',
      'lc:1004',
      'lc:1658',
      'lc:30',
    ],
  },
  {
    id: 'binary-search',
    title: '二分搜索',
    groupId: 'two-pointer-group',
    difficulty: 'medium',
    problemIds: [
      'lc:33',
      'lc:34',
      'lc:35',
      'lc:74',
      'lc:81',
      'lc:162',
      'lc:240',
      'lc:392',
      'lc:410',
      'lc:566',
      'lc:658',
      'lc:704',
      'lc:792',
      'lc:852',
      'lc:875',
      'lc:1011',
      'lc:4',
      'lc:69',
      'lc:153',
      'lc:287',
      'lc:lcr-172',
    ],
  },
  {
    id: 'random',
    title: '随机算法',
    groupId: 'two-pointer-group',
    difficulty: 'medium',
    problemIds: [
      'lc:382',
      'lc:384',
      'lc:398',
      'lc:528',
      'lc:lcr-071',
    ],
  },
  {
    id: 'two-pointer-linked',
    title: '链表双指针',
    difficulty: 'easy',
    problemIds: [
      'lc:2',
      'lc:19',
      'lc:21',
      'lc:23',
      'lc:82',
      'lc:86',
      'lc:141',
      'lc:142',
      'lc:160',
      'lc:373',
      'lc:378',
      'lc:445',
      'lc:876',
      'lc:lcr-140',
    ],
  },
  {
    id: 'recursion-ops',
    title: '递归',
    difficulty: 'medium',
    problemIds: [
      'lc:25',
      'lc:92',
      'lc:24',
      'lc:206',
      'lc:234',
    ],
  },
  {
    id: 'binary-tree',
    title: '二叉树',
    difficulty: 'medium',
    problemIds: [
      'lc:94',
      'lc:102',
      'lc:104',
      'lc:100',
      'lc:101',
      'lc:112',
      'lc:111',
      'lc:144',
      'lc:145',
      'lc:222',
      'lc:429',
      'lc:543',
      'lc:589',
      'lc:590',
    ],
  },
  {
    id: 'recursive-traverse',
    title: '递归遍历',
    difficulty: 'medium',
    problemIds: [
      'lc:104',
      'lc:105',
      'lc:106',
      'lc:114',
      'lc:116',
      'lc:129',
      'lc:199',
      'lc:226',
      'lc:235',
      'lc:236',
      'lc:257',
      'lc:297',
      'lc:331',
      'lc:437',
      'lc:124',
      'lc:654',
      'lc:872',
      'lc:889',
      'lc:894',
      'lc:988',
      'lc:998',
      'lc:1022',
      'lc:1110',
      'lc:1457',
      'lc:1644',
      'lc:1650',
      'lc:1676',
    ],
  },
  {
    id: 'level-order-traverse',
    title: '层序遍历',
    difficulty: 'medium',
    problemIds: [
      'lc:94',
      'lc:102',
      'lc:103',
      'lc:107',
      'lc:117',
      'lc:144',
      'lc:145',
      'lc:515',
      'lc:637',
      'lc:662',
      'lc:958',
      'lc:1161',
      'lc:1302',
      'lc:1609',
    ],
  },
  {
    id: 'math',
    title: '数学',
    groupId: 'other-group',
    difficulty: 'medium',
    problemIds: [
      'lc:8',
      'lc:9',
      'lc:50',
      'lc:12',
      'lc:13',
      'lc:66',
      'lc:67',
      'lc:149',
      'lc:172',
      'lc:202',
      'lc:204',
      'lc:263',
      'lc:264',
      'lc:292',
      'lc:306',
      'lc:313',
      'lc:319',
      'lc:357',
      'lc:372',
      'lc:400',
      'lc:793',
      'lc:842',
      'lc:877',
      'lc:1201',
    ],
  },
  {
    id: 'greedy',
    title: '贪心算法',
    groupId: 'other-group',
    difficulty: 'medium',
    problemIds: [
      'lc:45',
      'lc:55',
      'lc:121',
      'lc:122',
      'lc:134',
      'lc:135',
      'lc:253',
      'lc:435',
      'lc:452',
      'lc:763',
      'lc:1235',
    ],
  },
  {
    id: 'bitwise',
    title: '位运算',
    groupId: 'other-group',
    difficulty: 'medium',
    problemIds: [
      'lc:137',
      'lc:190',
      'lc:191',
      'lc:201',
    ],
  },
  {
    id: 'dfs',
    title: '深度优先搜索',
    groupId: 'traverse-view-group',
    difficulty: 'hard',
    problemIds: [
      'lc:200',
      'lc:694',
      'lc:695',
      'lc:1020',
      'lc:1254',
      'lc:1905',
    ],
  },
  {
    id: 'backtracking',
    title: '回溯算法',
    groupId: 'traverse-view-group',
    difficulty: 'hard',
    problemIds: [
      'lc:17',
      'lc:37',
      'lc:39',
      'lc:40',
      'lc:46',
      'lc:47',
      'lc:51',
      'lc:52',
      'lc:22',
      'lc:77',
      'lc:78',
      'lc:79',
      'lc:89',
      'lc:90',
      'lc:93',
      'lc:131',
      'lc:216',
      'lc:473',
      'lc:491',
      'lc:526',
      'lc:967',
      'lc:980',
      'lc:lcr-082',
      'lc:lcr-084',
    ],
  },
  {
    id: 'divide-conquer',
    title: '分治算法',
    groupId: 'subproblem-view-group',
    difficulty: 'hard',
    problemIds: [
      'lc:23',
      'lc:148',
      'lc:427',
      'lc:912',
    ],
  },
  {
    id: 'dp',
    title: '动态规划',
    groupId: 'subproblem-view-group',
    difficulty: 'hard',
    problemIds: [
      'lc:53',
      'lc:72',
      'lc:62',
      'lc:63',
      'lc:64',
      'lc:70',
      'lc:97',
      'lc:118',
      'lc:120',
      'lc:123',
      'lc:198',
      'lc:139',
      'lc:213',
      'lc:279',
      'lc:300',
      'lc:322',
      'lc:152',
      'lc:188',
      'lc:221',
      'lc:337',
      'lc:354',
      'lc:416',
      'lc:494',
      'lc:509',
      'lc:516',
      'lc:518',
      'lc:583',
      'lc:712',
      'lc:931',
      'lc:1143',
      'lc:1312',
    ],
  },
  {
    id: 'bfs',
    title: '广度优先搜索',
    difficulty: 'hard',
    problemIds: [
      'lc:117',
      'lc:310',
      'lc:433',
      'lc:127',
      'lc:662',
      'lc:752',
      'lc:773',
      'lc:841',
      'lc:863',
      'lc:919',
      'lc:1091',
      'lc:1306',
      'lc:1926',
      'lc:909',
      'lc:994',
    ],
  },
  {
    id: 'shortest-path',
    title: '最短路径',
    difficulty: 'hard',
    problemIds: [
      'lc:743',
      'lc:787',
      'lc:1368',
      'lc:1514',
      'lc:1631',
    ],
  },
  {
    id: 'bst',
    title: '二叉搜索树',
    groupId: 'advanced-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:95',
      'lc:96',
      'lc:98',
      'lc:108',
      'lc:173',
      'lc:230',
      'lc:450',
      'lc:530',
      'lc:538',
      'lc:700',
      'lc:701',
      'lc:1038',
      'lc:1373',
    ],
  },
  {
    id: 'heap',
    title: '堆',
    groupId: 'advanced-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:23',
      'lc:215',
      'lc:295',
      'lc:502',
      'lc:313',
      'lc:347',
      'lc:355',
      'lc:373',
      'lc:378',
      'lc:451',
      'lc:692',
      'lc:703',
      'lc:870',
      'lc:1834',
      'lc:1845',
    ],
  },
  {
    id: 'trie',
    title: '字典树',
    groupId: 'advanced-ds-group',
    difficulty: 'medium',
    problemIds: [
      'lc:208',
      'lc:211',
      'lc:212',
      'lc:648',
      'lc:677',
      'lc:1804',
    ],
  },
  {
    id: 'graph',
    title: '图',
    groupId: 'advanced-ds-group',
    difficulty: 'hard',
    problemIds: [
      'lc:130',
      'lc:133',
      'lc:399',
      'lc:207',
      'lc:210',
      'lc:261',
      'lc:323',
      'lc:547',
      'lc:785',
      'lc:886',
      'lc:947',
      'lc:990',
      'lc:1135',
      'lc:1361',
      'lc:1584',
      'lc:lcr-106',
    ],
  },
]

const KNOWLEDGE_TOPICS: AlgorithmKnowledgeData['topics'] = KNOWLEDGE_TOPICS_RAW
  .map(topic => ({
    ...topic,
    title: CHECKIN_TOPIC_TITLE[topic.id] ?? topic.title,
  }))
  .sort(
    (a, b) =>
      (CHECKIN_TOPIC_ORDER.get(a.id) ?? Number.MAX_SAFE_INTEGER)
      - (CHECKIN_TOPIC_ORDER.get(b.id) ?? Number.MAX_SAFE_INTEGER),
  )

/// keep-sorted
const KNOWLEDGE_PROBLEMS_BASE: AlgorithmKnowledgeData['problems'] = {
  'lc:1': {
    id: 'lc:1',
    number: '1',
    slug: 'two-sum',
    title: '两数之和',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:2': {
    id: 'lc:2',
    number: '2',
    slug: 'add-two-numbers',
    title: '两数相加',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:3': {
    id: 'lc:3',
    number: '3',
    slug: 'longest-substring-without-repeating-characters',
    title: '无重复字符的最长子串',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:5': {
    id: 'lc:5',
    number: '5',
    slug: 'longest-palindromic-substring',
    title: '最长回文子串',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:8': {
    id: 'lc:8',
    number: '8',
    slug: 'string-to-integer-atoi',
    title: '字符串转换整数 (atoi)',
    difficulty: 'medium',
  },
  'lc:9': {
    id: 'lc:9',
    number: '9',
    slug: 'palindrome-number',
    title: '回文数',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:11': {
    id: 'lc:11',
    number: '11',
    slug: 'container-with-most-water',
    title: '盛最多水的容器',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:14': {
    id: 'lc:14',
    number: '14',
    slug: 'longest-common-prefix',
    title: '最长公共前缀',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:15': {
    id: 'lc:15',
    number: '15',
    slug: '3sum',
    title: '三数之和',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:17': {
    id: 'lc:17',
    number: '17',
    slug: 'letter-combinations-of-a-phone-number',
    title: '电话号码的字母组合',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:18': {
    id: 'lc:18',
    number: '18',
    slug: '4sum',
    title: '四数之和',
    difficulty: 'medium',
  },
  'lc:19': {
    id: 'lc:19',
    number: '19',
    slug: 'remove-nth-node-from-end-of-list',
    title: '删除链表的倒数第 N 个结点',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:20': {
    id: 'lc:20',
    number: '20',
    slug: 'valid-parentheses',
    title: '有效的括号',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:21': {
    id: 'lc:21',
    number: '21',
    slug: 'merge-two-sorted-lists',
    title: '合并两个有序链表',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:23': {
    id: 'lc:23',
    number: '23',
    slug: 'merge-k-sorted-lists',
    title: '合并 K 个升序链表',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:25': {
    id: 'lc:25',
    number: '25',
    slug: 'reverse-nodes-in-k-group',
    title: 'K 个一组翻转链表',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:26': {
    id: 'lc:26',
    number: '26',
    slug: 'remove-duplicates-from-sorted-array',
    title: '删除有序数组中的重复项',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:27': {
    id: 'lc:27',
    number: '27',
    slug: 'remove-element',
    title: '移除元素',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:33': {
    id: 'lc:33',
    number: '33',
    slug: 'search-in-rotated-sorted-array',
    title: '搜索旋转排序数组',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:34': {
    id: 'lc:34',
    number: '34',
    slug: 'find-first-and-last-position-of-element-in-sorted-array',
    title: '在排序数组中查找元素的第一个和最后一个位置',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:35': {
    id: 'lc:35',
    number: '35',
    slug: 'search-insert-position',
    title: '搜索插入位置',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:37': {
    id: 'lc:37',
    number: '37',
    slug: 'sudoku-solver',
    title: '解数独',
    difficulty: 'hard',
  },
  'lc:39': {
    id: 'lc:39',
    number: '39',
    slug: 'combination-sum',
    title: '组合总和',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:40': {
    id: 'lc:40',
    number: '40',
    slug: 'combination-sum-ii',
    title: '组合总和 II',
    difficulty: 'medium',
  },
  'lc:42': {
    id: 'lc:42',
    number: '42',
    slug: 'trapping-rain-water',
    title: '接雨水',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:45': {
    id: 'lc:45',
    number: '45',
    slug: 'jump-game-ii',
    title: '跳跃游戏 II',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:46': {
    id: 'lc:46',
    number: '46',
    slug: 'permutations',
    title: '全排列',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:47': {
    id: 'lc:47',
    number: '47',
    slug: 'permutations-ii',
    title: '全排列 II',
    difficulty: 'medium',
  },
  'lc:48': {
    id: 'lc:48',
    number: '48',
    slug: 'rotate-image',
    title: '旋转图像',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:49': {
    id: 'lc:49',
    number: '49',
    slug: 'group-anagrams',
    title: '字母异位词分组',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:50': {
    id: 'lc:50',
    number: '50',
    slug: 'powx-n',
    title: 'x 的 n 次幂',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:51': {
    id: 'lc:51',
    number: '51',
    slug: 'n-queens',
    title: 'N 皇后',
    difficulty: 'hard',
    tags: ['hot100'],
  },
  'lc:52': {
    id: 'lc:52',
    number: '52',
    slug: 'n-queens-ii',
    title: 'N 皇后 II',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:53': {
    id: 'lc:53',
    number: '53',
    slug: 'maximum-subarray',
    title: '最大子数组和',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:54': {
    id: 'lc:54',
    number: '54',
    slug: 'spiral-matrix',
    title: '螺旋矩阵',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:55': {
    id: 'lc:55',
    number: '55',
    slug: 'jump-game',
    title: '跳跃游戏',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:59': {
    id: 'lc:59',
    number: '59',
    slug: 'spiral-matrix-ii',
    title: '螺旋矩阵 II',
    difficulty: 'medium',
  },
  'lc:61': {
    id: 'lc:61',
    number: '61',
    slug: 'rotate-list',
    title: '旋转链表',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:67': {
    id: 'lc:67',
    number: '67',
    slug: 'add-binary',
    title: '二进制求和',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:71': {
    id: 'lc:71',
    number: '71',
    slug: 'simplify-path',
    title: '简化路径',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:72': {
    id: 'lc:72',
    number: '72',
    slug: 'edit-distance',
    title: '编辑距离',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:74': {
    id: 'lc:74',
    number: '74',
    slug: 'search-a-2d-matrix',
    title: '搜索二维矩阵',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:75': {
    id: 'lc:75',
    number: '75',
    slug: 'sort-colors',
    title: '颜色分类',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:76': {
    id: 'lc:76',
    number: '76',
    slug: 'minimum-window-substring',
    title: '最小覆盖子串',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:77': {
    id: 'lc:77',
    number: '77',
    slug: 'combinations',
    title: '组合',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:78': {
    id: 'lc:78',
    number: '78',
    slug: 'subsets',
    title: '子集',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:79': {
    id: 'lc:79',
    number: '79',
    slug: 'word-search',
    title: '单词搜索',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:80': {
    id: 'lc:80',
    number: '80',
    slug: 'remove-duplicates-from-sorted-array-ii',
    title: '删除有序数组中的重复项 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:81': {
    id: 'lc:81',
    number: '81',
    slug: 'search-in-rotated-sorted-array-ii',
    title: '搜索旋转排序数组 II',
    difficulty: 'medium',
  },
  'lc:82': {
    id: 'lc:82',
    number: '82',
    slug: 'remove-duplicates-from-sorted-list-ii',
    title: '删除排序链表中的重复元素 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:83': {
    id: 'lc:83',
    number: '83',
    slug: 'remove-duplicates-from-sorted-list',
    title: '删除排序链表中的重复元素',
    difficulty: 'easy',
  },
  'lc:86': {
    id: 'lc:86',
    number: '86',
    slug: 'partition-list',
    title: '分隔链表',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:88': {
    id: 'lc:88',
    number: '88',
    slug: 'merge-sorted-array',
    title: '合并两个有序数组',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:89': {
    id: 'lc:89',
    number: '89',
    slug: 'gray-code',
    title: '格雷编码',
    difficulty: 'medium',
  },
  'lc:90': {
    id: 'lc:90',
    number: '90',
    slug: 'subsets-ii',
    title: '子集 II',
    difficulty: 'medium',
  },
  'lc:92': {
    id: 'lc:92',
    number: '92',
    slug: 'reverse-linked-list-ii',
    title: '反转链表 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:93': {
    id: 'lc:93',
    number: '93',
    slug: 'restore-ip-addresses',
    title: '复原 IP 地址',
    difficulty: 'medium',
  },
  'lc:94': {
    id: 'lc:94',
    number: '94',
    slug: 'binary-tree-inorder-traversal',
    title: '二叉树的中序遍历',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:95': {
    id: 'lc:95',
    number: '95',
    slug: 'unique-binary-search-trees-ii',
    title: '不同的二叉搜索树 II',
    difficulty: 'medium',
  },
  'lc:96': {
    id: 'lc:96',
    number: '96',
    slug: 'unique-binary-search-trees',
    title: '不同的二叉搜索树',
    difficulty: 'medium',
  },
  'lc:98': {
    id: 'lc:98',
    number: '98',
    slug: 'validate-binary-search-tree',
    title: '验证二叉搜索树',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:102': {
    id: 'lc:102',
    number: '102',
    slug: 'binary-tree-level-order-traversal',
    title: '二叉树的层序遍历',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:103': {
    id: 'lc:103',
    number: '103',
    slug: 'binary-tree-zigzag-level-order-traversal',
    title: '二叉树的锯齿形层序遍历',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:104': {
    id: 'lc:104',
    number: '104',
    slug: 'maximum-depth-of-binary-tree',
    title: '二叉树的最大深度',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:105': {
    id: 'lc:105',
    number: '105',
    slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
    title: '从前序与中序遍历序列构造二叉树',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:106': {
    id: 'lc:106',
    number: '106',
    slug: 'construct-binary-tree-from-inorder-and-postorder-traversal',
    title: '从中序与后序遍历序列构造二叉树',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:107': {
    id: 'lc:107',
    number: '107',
    slug: 'binary-tree-level-order-traversal-ii',
    title: '二叉树的层序遍历 II',
    difficulty: 'medium',
  },
  'lc:111': {
    id: 'lc:111',
    number: '111',
    slug: 'minimum-depth-of-binary-tree',
    title: '二叉树的最小深度',
    difficulty: 'easy',
  },
  'lc:114': {
    id: 'lc:114',
    number: '114',
    slug: 'flatten-binary-tree-to-linked-list',
    title: '二叉树展开为链表',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:116': {
    id: 'lc:116',
    number: '116',
    slug: 'populating-next-right-pointers-in-each-node',
    title: '填充每个节点的下一个右侧节点指针',
    difficulty: 'medium',
  },
  'lc:117': {
    id: 'lc:117',
    number: '117',
    slug: 'populating-next-right-pointers-in-each-node-ii',
    title: '填充每个节点的下一个右侧节点指针 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:125': {
    id: 'lc:125',
    number: '125',
    slug: 'valid-palindrome',
    title: '验证回文串',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:128': {
    id: 'lc:128',
    number: '128',
    slug: 'longest-consecutive-sequence',
    title: '最长连续序列',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:129': {
    id: 'lc:129',
    number: '129',
    slug: 'sum-root-to-leaf-numbers',
    title: '求根节点到叶节点数字之和',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:130': {
    id: 'lc:130',
    number: '130',
    slug: 'surrounded-regions',
    title: '被围绕的区域',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:131': {
    id: 'lc:131',
    number: '131',
    slug: 'palindrome-partitioning',
    title: '分割回文串',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:133': {
    id: 'lc:133',
    number: '133',
    slug: 'clone-graph',
    title: '克隆图',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:134': {
    id: 'lc:134',
    number: '134',
    slug: 'gas-station',
    title: '加油站',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:136': {
    id: 'lc:136',
    number: '136',
    slug: 'single-number',
    title: '只出现一次的数字',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:138': {
    id: 'lc:138',
    number: '138',
    slug: 'copy-list-with-random-pointer',
    title: '随机链表的复制',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:141': {
    id: 'lc:141',
    number: '141',
    slug: 'linked-list-cycle',
    title: '环形链表',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:142': {
    id: 'lc:142',
    number: '142',
    slug: 'linked-list-cycle-ii',
    title: '环形链表 II',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:143': {
    id: 'lc:143',
    number: '143',
    slug: 'reorder-list',
    title: '重排链表',
    difficulty: 'medium',
  },
  'lc:144': {
    id: 'lc:144',
    number: '144',
    slug: 'binary-tree-preorder-traversal',
    title: '二叉树的前序遍历',
    difficulty: 'easy',
  },
  'lc:145': {
    id: 'lc:145',
    number: '145',
    slug: 'binary-tree-postorder-traversal',
    title: '二叉树的后序遍历',
    difficulty: 'easy',
  },
  'lc:146': {
    id: 'lc:146',
    number: '146',
    slug: 'lru-cache',
    title: 'LRU 缓存',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:150': {
    id: 'lc:150',
    number: '150',
    slug: 'evaluate-reverse-polish-notation',
    title: '逆波兰表达式求值',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:151': {
    id: 'lc:151',
    number: '151',
    slug: 'reverse-words-in-a-string',
    title: '反转字符串中的单词',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:155': {
    id: 'lc:155',
    number: '155',
    slug: 'min-stack',
    title: '最小栈',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:160': {
    id: 'lc:160',
    number: '160',
    slug: 'intersection-of-two-linked-lists',
    title: '相交链表',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:162': {
    id: 'lc:162',
    number: '162',
    slug: 'find-peak-element',
    title: '寻找峰值',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:167': {
    id: 'lc:167',
    number: '167',
    slug: 'two-sum-ii-input-array-is-sorted',
    title: '两数之和 II - 输入有序数组',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:169': {
    id: 'lc:169',
    number: '169',
    slug: 'majority-element',
    title: '多数元素',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:172': {
    id: 'lc:172',
    number: '172',
    slug: 'factorial-trailing-zeroes',
    title: '阶乘后的零',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:198': {
    id: 'lc:198',
    number: '198',
    slug: 'house-robber',
    title: '打家劫舍',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:199': {
    id: 'lc:199',
    number: '199',
    slug: 'binary-tree-right-side-view',
    title: '二叉树的右视图',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:200': {
    id: 'lc:200',
    number: '200',
    slug: 'number-of-islands',
    title: '岛屿数量',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:204': {
    id: 'lc:204',
    number: '204',
    slug: 'count-primes',
    title: '计数质数',
    difficulty: 'medium',
  },
  'lc:206': {
    id: 'lc:206',
    number: '206',
    slug: 'reverse-linked-list',
    title: '反转链表',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:207': {
    id: 'lc:207',
    number: '207',
    slug: 'course-schedule',
    title: '课程表',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:208': {
    id: 'lc:208',
    number: '208',
    slug: 'implement-trie-prefix-tree',
    title: '实现 Trie (前缀树)',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:209': {
    id: 'lc:209',
    number: '209',
    slug: 'minimum-size-subarray-sum',
    title: '长度最小的子数组',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:210': {
    id: 'lc:210',
    number: '210',
    slug: 'course-schedule-ii',
    title: '课程表 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:211': {
    id: 'lc:211',
    number: '211',
    slug: 'design-add-and-search-words-data-structure',
    title: '添加与搜索单词 - 数据结构设计',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:213': {
    id: 'lc:213',
    number: '213',
    slug: 'house-robber-ii',
    title: '打家劫舍 II',
    difficulty: 'medium',
  },
  'lc:215': {
    id: 'lc:215',
    number: '215',
    slug: 'kth-largest-element-in-an-array',
    title: '数组中的第K个最大元素',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:216': {
    id: 'lc:216',
    number: '216',
    slug: 'combination-sum-iii',
    title: '组合总和 III',
    difficulty: 'medium',
  },
  'lc:217': {
    id: 'lc:217',
    number: '217',
    slug: 'contains-duplicate',
    title: '存在重复元素',
    difficulty: 'easy',
  },
  'lc:219': {
    id: 'lc:219',
    number: '219',
    slug: 'contains-duplicate-ii',
    title: '存在重复元素 II',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:220': {
    id: 'lc:220',
    number: '220',
    slug: 'contains-duplicate-iii',
    title: '存在重复元素 III',
    difficulty: 'hard',
  },
  'lc:222': {
    id: 'lc:222',
    number: '222',
    slug: 'count-complete-tree-nodes',
    title: '完全二叉树的节点个数',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:224': {
    id: 'lc:224',
    number: '224',
    slug: 'basic-calculator',
    title: '基本计算器',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:225': {
    id: 'lc:225',
    number: '225',
    slug: 'implement-stack-using-queues',
    title: '用队列实现栈',
    difficulty: 'easy',
  },
  'lc:226': {
    id: 'lc:226',
    number: '226',
    slug: 'invert-binary-tree',
    title: '翻转二叉树',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:227': {
    id: 'lc:227',
    number: '227',
    slug: 'basic-calculator-ii',
    title: '基本计算器 II',
    difficulty: 'medium',
  },
  'lc:230': {
    id: 'lc:230',
    number: '230',
    slug: 'kth-smallest-element-in-a-bst',
    title: '二叉搜索树中第K小的元素',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:232': {
    id: 'lc:232',
    number: '232',
    slug: 'implement-queue-using-stacks',
    title: '用栈实现队列',
    difficulty: 'easy',
  },
  'lc:234': {
    id: 'lc:234',
    number: '234',
    slug: 'palindrome-linked-list',
    title: '回文链表',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:235': {
    id: 'lc:235',
    number: '235',
    slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    title: '二叉搜索树的最近公共祖先',
    difficulty: 'medium',
  },
  'lc:236': {
    id: 'lc:236',
    number: '236',
    slug: 'lowest-common-ancestor-of-a-binary-tree',
    title: '二叉树的最近公共祖先',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:238': {
    id: 'lc:238',
    number: '238',
    slug: 'product-of-array-except-self',
    title: '除自身以外数组的乘积',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:239': {
    id: 'lc:239',
    number: '239',
    slug: 'sliding-window-maximum',
    title: '滑动窗口最大值',
    difficulty: 'hard',
    tags: ['hot100'],
  },
  'lc:240': {
    id: 'lc:240',
    number: '240',
    slug: 'search-a-2d-matrix-ii',
    title: '搜索二维矩阵 II',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:242': {
    id: 'lc:242',
    number: '242',
    slug: 'valid-anagram',
    title: '有效的字母异位词',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:253': {
    id: 'lc:253',
    number: '253',
    slug: 'meeting-rooms-ii',
    title: '会议室 II',
    difficulty: 'medium',
  },
  'lc:257': {
    id: 'lc:257',
    number: '257',
    slug: 'binary-tree-paths',
    title: '二叉树的所有路径',
    difficulty: 'easy',
  },
  'lc:261': {
    id: 'lc:261',
    number: '261',
    slug: 'graph-valid-tree',
    title: '以图判树',
    difficulty: 'medium',
  },
  'lc:263': {
    id: 'lc:263',
    number: '263',
    slug: 'ugly-number',
    title: '丑数',
    difficulty: 'easy',
  },
  'lc:264': {
    id: 'lc:264',
    number: '264',
    slug: 'ugly-number-ii',
    title: '丑数 II',
    difficulty: 'medium',
  },
  'lc:279': {
    id: 'lc:279',
    number: '279',
    slug: 'perfect-squares',
    title: '完全平方数',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:283': {
    id: 'lc:283',
    number: '283',
    slug: 'move-zeroes',
    title: '移动零',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:284': {
    id: 'lc:284',
    number: '284',
    slug: 'peeking-iterator',
    title: '窥视迭代器',
    difficulty: 'medium',
  },
  'lc:290': {
    id: 'lc:290',
    number: '290',
    slug: 'word-pattern',
    title: '单词规律',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:292': {
    id: 'lc:292',
    number: '292',
    slug: 'nim-game',
    title: 'Nim 游戏',
    difficulty: 'easy',
  },
  'lc:295': {
    id: 'lc:295',
    number: '295',
    slug: 'find-median-from-data-stream',
    title: '数据流的中位数',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:297': {
    id: 'lc:297',
    number: '297',
    slug: 'serialize-and-deserialize-binary-tree',
    title: '二叉树的序列化与反序列化',
    difficulty: 'hard',
  },
  'lc:300': {
    id: 'lc:300',
    number: '300',
    slug: 'longest-increasing-subsequence',
    title: '最长递增子序列',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:303': {
    id: 'lc:303',
    number: '303',
    slug: 'range-sum-query-immutable',
    title: '区域和检索 - 数组不可变',
    difficulty: 'easy',
  },
  'lc:304': {
    id: 'lc:304',
    number: '304',
    slug: 'range-sum-query-2d-immutable',
    title: '二维区域和检索 - 矩阵不可变',
    difficulty: 'medium',
  },
  'lc:306': {
    id: 'lc:306',
    number: '306',
    slug: 'additive-number',
    title: '累加数',
    difficulty: 'medium',
  },
  'lc:310': {
    id: 'lc:310',
    number: '310',
    slug: 'minimum-height-trees',
    title: '最小高度树',
    difficulty: 'medium',
  },
  'lc:313': {
    id: 'lc:313',
    number: '313',
    slug: 'super-ugly-number',
    title: '超级丑数',
    difficulty: 'medium',
  },
  'lc:319': {
    id: 'lc:319',
    number: '319',
    slug: 'bulb-switcher',
    title: '灯泡开关',
    difficulty: 'medium',
  },
  'lc:322': {
    id: 'lc:322',
    number: '322',
    slug: 'coin-change',
    title: '零钱兑换',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:323': {
    id: 'lc:323',
    number: '323',
    slug: 'number-of-connected-components-in-an-undirected-graph',
    title: '无向图中连通分量的数目',
    difficulty: 'medium',
  },
  'lc:331': {
    id: 'lc:331',
    number: '331',
    slug: 'verify-preorder-serialization-of-a-binary-tree',
    title: '验证二叉树的前序序列化',
    difficulty: 'medium',
  },
  'lc:337': {
    id: 'lc:337',
    number: '337',
    slug: 'house-robber-iii',
    title: '打家劫舍 III',
    difficulty: 'medium',
  },
  'lc:344': {
    id: 'lc:344',
    number: '344',
    slug: 'reverse-string',
    title: '反转字符串',
    difficulty: 'easy',
  },
  'lc:347': {
    id: 'lc:347',
    number: '347',
    slug: 'top-k-frequent-elements',
    title: '前 K 个高频元素',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:354': {
    id: 'lc:354',
    number: '354',
    slug: 'russian-doll-envelopes',
    title: '俄罗斯套娃信封问题',
    difficulty: 'hard',
  },
  'lc:355': {
    id: 'lc:355',
    number: '355',
    slug: 'design-twitter',
    title: '设计推特',
    difficulty: 'medium',
  },
  'lc:357': {
    id: 'lc:357',
    number: '357',
    slug: 'count-numbers-with-unique-digits',
    title: '统计各位数字都不同的数字个数',
    difficulty: 'medium',
  },
  'lc:370': {
    id: 'lc:370',
    number: '370',
    slug: 'range-addition',
    title: '区间加法',
    difficulty: 'medium',
  },
  'lc:372': {
    id: 'lc:372',
    number: '372',
    slug: 'super-pow',
    title: '超级次方',
    difficulty: 'medium',
  },
  'lc:373': {
    id: 'lc:373',
    number: '373',
    slug: 'find-k-pairs-with-smallest-sums',
    title: '查找和最小的 K 对数字',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:378': {
    id: 'lc:378',
    number: '378',
    slug: 'kth-smallest-element-in-a-sorted-matrix',
    title: '有序矩阵中第 K 小的元素',
    difficulty: 'medium',
  },
  'lc:382': {
    id: 'lc:382',
    number: '382',
    slug: 'linked-list-random-node',
    title: '链表随机节点',
    difficulty: 'medium',
  },
  'lc:384': {
    id: 'lc:384',
    number: '384',
    slug: 'shuffle-an-array',
    title: '打乱数组',
    difficulty: 'medium',
  },
  'lc:387': {
    id: 'lc:387',
    number: '387',
    slug: 'first-unique-character-in-a-string',
    title: '字符串中的第一个唯一字符',
    difficulty: 'easy',
  },
  'lc:388': {
    id: 'lc:388',
    number: '388',
    slug: 'longest-absolute-file-path',
    title: '文件的最长绝对路径',
    difficulty: 'medium',
  },
  'lc:389': {
    id: 'lc:389',
    number: '389',
    slug: 'find-the-difference',
    title: '找不同',
    difficulty: 'easy',
  },
  'lc:392': {
    id: 'lc:392',
    number: '392',
    slug: 'is-subsequence',
    title: '判断子序列',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:395': {
    id: 'lc:395',
    number: '395',
    slug: 'longest-substring-with-at-least-k-repeating-characters',
    title: '至少有 K 个重复字符的最长子串',
    difficulty: 'medium',
  },
  'lc:398': {
    id: 'lc:398',
    number: '398',
    slug: 'random-pick-index',
    title: '随机数索引',
    difficulty: 'medium',
  },
  'lc:400': {
    id: 'lc:400',
    number: '400',
    slug: 'nth-digit',
    title: '第 N 位数字',
    difficulty: 'medium',
  },
  'lc:402': {
    id: 'lc:402',
    number: '402',
    slug: 'remove-k-digits',
    title: '移掉 K 位数字',
    difficulty: 'medium',
  },
  'lc:410': {
    id: 'lc:410',
    number: '410',
    slug: 'split-array-largest-sum',
    title: '分割数组的最大值',
    difficulty: 'hard',
  },
  'lc:416': {
    id: 'lc:416',
    number: '416',
    slug: 'partition-equal-subset-sum',
    title: '分割等和子集',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:424': {
    id: 'lc:424',
    number: '424',
    slug: 'longest-repeating-character-replacement',
    title: '替换后的最长重复字符',
    difficulty: 'medium',
  },
  'lc:429': {
    id: 'lc:429',
    number: '429',
    slug: 'n-ary-tree-level-order-traversal',
    title: 'N 叉树的层序遍历',
    difficulty: 'medium',
  },
  'lc:433': {
    id: 'lc:433',
    number: '433',
    slug: 'minimum-genetic-mutation',
    title: '最小基因变化',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:435': {
    id: 'lc:435',
    number: '435',
    slug: 'non-overlapping-intervals',
    title: '无重叠区间',
    difficulty: 'medium',
  },
  'lc:438': {
    id: 'lc:438',
    number: '438',
    slug: 'find-all-anagrams-in-a-string',
    title: '找到字符串中所有字母异位词',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:442': {
    id: 'lc:442',
    number: '442',
    slug: 'find-all-duplicates-in-an-array',
    title: '数组中重复的数据',
    difficulty: 'medium',
  },
  'lc:445': {
    id: 'lc:445',
    number: '445',
    slug: 'add-two-numbers-ii',
    title: '两数相加 II',
    difficulty: 'medium',
  },
  'lc:448': {
    id: 'lc:448',
    number: '448',
    slug: 'find-all-numbers-disappeared-in-an-array',
    title: '找到所有数组中消失的数字',
    difficulty: 'easy',
  },
  'lc:450': {
    id: 'lc:450',
    number: '450',
    slug: 'delete-node-in-a-bst',
    title: '删除二叉搜索树中的节点',
    difficulty: 'medium',
  },
  'lc:451': {
    id: 'lc:451',
    number: '451',
    slug: 'sort-characters-by-frequency',
    title: '根据字符出现频率排序',
    difficulty: 'medium',
  },
  'lc:452': {
    id: 'lc:452',
    number: '452',
    slug: 'minimum-number-of-arrows-to-burst-balloons',
    title: '用最少数量的箭引爆气球',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:473': {
    id: 'lc:473',
    number: '473',
    slug: 'matchsticks-to-square',
    title: '火柴拼正方形',
    difficulty: 'medium',
  },
  'lc:491': {
    id: 'lc:491',
    number: '491',
    slug: 'non-decreasing-subsequences',
    title: '非递减子序列',
    difficulty: 'medium',
  },
  'lc:494': {
    id: 'lc:494',
    number: '494',
    slug: 'target-sum',
    title: '目标和',
    difficulty: 'medium',
  },
  'lc:496': {
    id: 'lc:496',
    number: '496',
    slug: 'next-greater-element-i',
    title: '下一个更大元素 I',
    difficulty: 'easy',
  },
  'lc:503': {
    id: 'lc:503',
    number: '503',
    slug: 'next-greater-element-ii',
    title: '下一个更大元素 II',
    difficulty: 'medium',
  },
  'lc:509': {
    id: 'lc:509',
    number: '509',
    slug: 'fibonacci-number',
    title: '斐波那契数',
    difficulty: 'easy',
  },
  'lc:515': {
    id: 'lc:515',
    number: '515',
    slug: 'find-largest-value-in-each-tree-row',
    title: '在每个树行中找最大值',
    difficulty: 'medium',
  },
  'lc:516': {
    id: 'lc:516',
    number: '516',
    slug: 'longest-palindromic-subsequence',
    title: '最长回文子序列',
    difficulty: 'medium',
  },
  'lc:518': {
    id: 'lc:518',
    number: '518',
    slug: 'coin-change-ii',
    title: '零钱兑换 II',
    difficulty: 'medium',
  },
  'lc:519': {
    id: 'lc:519',
    number: '519',
    slug: 'random-flip-matrix',
    title: '随机翻转矩阵',
    difficulty: 'medium',
  },
  'lc:523': {
    id: 'lc:523',
    number: '523',
    slug: 'continuous-subarray-sum',
    title: '连续的子数组和',
    difficulty: 'medium',
  },
  'lc:525': {
    id: 'lc:525',
    number: '525',
    slug: 'contiguous-array',
    title: '连续数组',
    difficulty: 'medium',
  },
  'lc:526': {
    id: 'lc:526',
    number: '526',
    slug: 'beautiful-arrangement',
    title: '优美的排列',
    difficulty: 'medium',
  },
  'lc:528': {
    id: 'lc:528',
    number: '528',
    slug: 'random-pick-with-weight',
    title: '按权重随机选择',
    difficulty: 'medium',
  },
  'lc:538': {
    id: 'lc:538',
    number: '538',
    slug: 'convert-bst-to-greater-tree',
    title: '把二叉搜索树转换为累加树',
    difficulty: 'medium',
  },
  'lc:543': {
    id: 'lc:543',
    number: '543',
    slug: 'diameter-of-binary-tree',
    title: '二叉树的直径',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:547': {
    id: 'lc:547',
    number: '547',
    slug: 'number-of-provinces',
    title: '省份数量',
    difficulty: 'medium',
  },
  'lc:560': {
    id: 'lc:560',
    number: '560',
    slug: 'subarray-sum-equals-k',
    title: '和为 K 的子数组',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:566': {
    id: 'lc:566',
    number: '566',
    slug: 'reshape-the-matrix',
    title: '重塑矩阵',
    difficulty: 'easy',
  },
  'lc:567': {
    id: 'lc:567',
    number: '567',
    slug: 'permutation-in-string',
    title: '字符串的排列',
    difficulty: 'medium',
  },
  'lc:581': {
    id: 'lc:581',
    number: '581',
    slug: 'shortest-unsorted-continuous-subarray',
    title: '最短无序连续子数组',
    difficulty: 'medium',
  },
  'lc:583': {
    id: 'lc:583',
    number: '583',
    slug: 'delete-operation-for-two-strings',
    title: '两个字符串的删除操作',
    difficulty: 'medium',
  },
  'lc:589': {
    id: 'lc:589',
    number: '589',
    slug: 'n-ary-tree-preorder-traversal',
    title: 'N 叉树的前序遍历',
    difficulty: 'easy',
  },
  'lc:590': {
    id: 'lc:590',
    number: '590',
    slug: 'n-ary-tree-postorder-traversal',
    title: 'N 叉树的后序遍历',
    difficulty: 'easy',
  },
  'lc:622': {
    id: 'lc:622',
    number: '622',
    slug: 'design-circular-queue',
    title: '设计循环队列',
    difficulty: 'medium',
  },
  'lc:637': {
    id: 'lc:637',
    number: '637',
    slug: 'average-of-levels-in-binary-tree',
    title: '二叉树的层平均值',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:641': {
    id: 'lc:641',
    number: '641',
    slug: 'design-circular-deque',
    title: '设计循环双端队列',
    difficulty: 'medium',
  },
  'lc:648': {
    id: 'lc:648',
    number: '648',
    slug: 'replace-words',
    title: '单词替换',
    difficulty: 'medium',
  },
  'lc:654': {
    id: 'lc:654',
    number: '654',
    slug: 'maximum-binary-tree',
    title: '最大二叉树',
    difficulty: 'medium',
  },
  'lc:658': {
    id: 'lc:658',
    number: '658',
    slug: 'find-k-closest-elements',
    title: '找到 K 个最接近的元素',
    difficulty: 'medium',
  },
  'lc:662': {
    id: 'lc:662',
    number: '662',
    slug: 'maximum-width-of-binary-tree',
    title: '二叉树最大宽度',
    difficulty: 'medium',
  },
  'lc:677': {
    id: 'lc:677',
    number: '677',
    slug: 'map-sum-pairs',
    title: '键值映射',
    difficulty: 'medium',
  },
  'lc:692': {
    id: 'lc:692',
    number: '692',
    slug: 'top-k-frequent-words',
    title: '前K个高频单词',
    difficulty: 'medium',
  },
  'lc:694': {
    id: 'lc:694',
    number: '694',
    slug: 'number-of-distinct-islands',
    title: '不同岛屿的数量',
    difficulty: 'medium',
  },
  'lc:695': {
    id: 'lc:695',
    number: '695',
    slug: 'max-area-of-island',
    title: '岛屿的最大面积',
    difficulty: 'medium',
  },
  'lc:700': {
    id: 'lc:700',
    number: '700',
    slug: 'search-in-a-binary-search-tree',
    title: '二叉搜索树中的搜索',
    difficulty: 'easy',
  },
  'lc:701': {
    id: 'lc:701',
    number: '701',
    slug: 'insert-into-a-binary-search-tree',
    title: '二叉搜索树中的插入操作',
    difficulty: 'medium',
  },
  'lc:703': {
    id: 'lc:703',
    number: '703',
    slug: 'kth-largest-element-in-a-stream',
    title: '数据流中的第 K 大元素',
    difficulty: 'easy',
  },
  'lc:704': {
    id: 'lc:704',
    number: '704',
    slug: 'binary-search',
    title: '二分查找',
    difficulty: 'easy',
  },
  'lc:712': {
    id: 'lc:712',
    number: '712',
    slug: 'minimum-ascii-delete-sum-for-two-strings',
    title: '两个字符串的最小ASCII删除和',
    difficulty: 'medium',
  },
  'lc:713': {
    id: 'lc:713',
    number: '713',
    slug: 'subarray-product-less-than-k',
    title: '乘积小于 K 的子数组',
    difficulty: 'medium',
  },
  'lc:724': {
    id: 'lc:724',
    number: '724',
    slug: 'find-pivot-index',
    title: '寻找数组的中心下标',
    difficulty: 'easy',
  },
  'lc:729': {
    id: 'lc:729',
    number: '729',
    slug: 'my-calendar-i',
    title: '我的日程安排表 I',
    difficulty: 'medium',
  },
  'lc:739': {
    id: 'lc:739',
    number: '739',
    slug: 'daily-temperatures',
    title: '每日温度',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:743': {
    id: 'lc:743',
    number: '743',
    slug: 'network-delay-time',
    title: '网络延迟时间',
    difficulty: 'medium',
  },
  'lc:752': {
    id: 'lc:752',
    number: '752',
    slug: 'open-the-lock',
    title: '打开转盘锁',
    difficulty: 'medium',
  },
  'lc:772': {
    id: 'lc:772',
    number: '772',
    slug: 'basic-calculator-iii',
    title: '基本计算器 III',
    difficulty: 'hard',
  },
  'lc:773': {
    id: 'lc:773',
    number: '773',
    slug: 'sliding-puzzle',
    title: '滑动谜题',
    difficulty: 'hard',
  },
  'lc:785': {
    id: 'lc:785',
    number: '785',
    slug: 'is-graph-bipartite',
    title: '判断二分图',
    difficulty: 'medium',
  },
  'lc:787': {
    id: 'lc:787',
    number: '787',
    slug: 'cheapest-flights-within-k-stops',
    title: 'K 站中转内最便宜的航班',
    difficulty: 'medium',
  },
  'lc:792': {
    id: 'lc:792',
    number: '792',
    slug: 'number-of-matching-subsequences',
    title: '匹配子序列的单词数',
    difficulty: 'medium',
  },
  'lc:793': {
    id: 'lc:793',
    number: '793',
    slug: 'preimage-size-of-factorial-zeroes-function',
    title: '阶乘函数后 K 个零',
    difficulty: 'hard',
  },
  'lc:841': {
    id: 'lc:841',
    number: '841',
    slug: 'keys-and-rooms',
    title: '钥匙和房间',
    difficulty: 'medium',
  },
  'lc:842': {
    id: 'lc:842',
    number: '842',
    slug: 'split-array-into-fibonacci-sequence',
    title: '将数组拆分成斐波那契序列',
    difficulty: 'medium',
  },
  'lc:852': {
    id: 'lc:852',
    number: '852',
    slug: 'peak-index-in-a-mountain-array',
    title: '山脉数组的峰顶索引',
    difficulty: 'medium',
  },
  'lc:853': {
    id: 'lc:853',
    number: '853',
    slug: 'car-fleet',
    title: '车队',
    difficulty: 'medium',
  },
  'lc:862': {
    id: 'lc:862',
    number: '862',
    slug: 'shortest-subarray-with-sum-at-least-k',
    title: '和至少为 K 的最短子数组',
    difficulty: 'hard',
  },
  'lc:863': {
    id: 'lc:863',
    number: '863',
    slug: 'all-nodes-distance-k-in-binary-tree',
    title: '二叉树中所有距离为 K 的结点',
    difficulty: 'medium',
  },
  'lc:867': {
    id: 'lc:867',
    number: '867',
    slug: 'transpose-matrix',
    title: '转置矩阵',
    difficulty: 'easy',
  },
  'lc:870': {
    id: 'lc:870',
    number: '870',
    slug: 'advantage-shuffle',
    title: '优势洗牌',
    difficulty: 'medium',
  },
  'lc:872': {
    id: 'lc:872',
    number: '872',
    slug: 'leaf-similar-trees',
    title: '叶子相似的树',
    difficulty: 'easy',
  },
  'lc:875': {
    id: 'lc:875',
    number: '875',
    slug: 'koko-eating-bananas',
    title: '爱吃香蕉的珂珂',
    difficulty: 'medium',
  },
  'lc:876': {
    id: 'lc:876',
    number: '876',
    slug: 'middle-of-the-linked-list',
    title: '链表的中间结点',
    difficulty: 'easy',
  },
  'lc:877': {
    id: 'lc:877',
    number: '877',
    slug: 'stone-game',
    title: '石子游戏',
    difficulty: 'medium',
  },
  'lc:886': {
    id: 'lc:886',
    number: '886',
    slug: 'possible-bipartition',
    title: '可能的二分法',
    difficulty: 'medium',
  },
  'lc:889': {
    id: 'lc:889',
    number: '889',
    slug: 'construct-binary-tree-from-preorder-and-postorder-traversal',
    title: '根据前序和后序遍历构造二叉树',
    difficulty: 'medium',
  },
  'lc:894': {
    id: 'lc:894',
    number: '894',
    slug: 'all-possible-full-binary-trees',
    title: '所有可能的真二叉树',
    difficulty: 'medium',
  },
  'lc:895': {
    id: 'lc:895',
    number: '895',
    slug: 'maximum-frequency-stack',
    title: '最大频率栈',
    difficulty: 'hard',
  },
  'lc:901': {
    id: 'lc:901',
    number: '901',
    slug: 'online-stock-span',
    title: '股票价格跨度',
    difficulty: 'medium',
  },
  'lc:912': {
    id: 'lc:912',
    number: '912',
    slug: 'sort-an-array',
    title: '排序数组',
    difficulty: 'medium',
  },
  'lc:918': {
    id: 'lc:918',
    number: '918',
    slug: 'maximum-sum-circular-subarray',
    title: '环形子数组的最大和',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:919': {
    id: 'lc:919',
    number: '919',
    slug: 'complete-binary-tree-inserter',
    title: '完全二叉树插入器',
    difficulty: 'medium',
  },
  'lc:931': {
    id: 'lc:931',
    number: '931',
    slug: 'minimum-falling-path-sum',
    title: '下降路径最小和',
    difficulty: 'medium',
  },
  'lc:933': {
    id: 'lc:933',
    number: '933',
    slug: 'number-of-recent-calls',
    title: '最近的请求次数',
    difficulty: 'easy',
  },
  'lc:947': {
    id: 'lc:947',
    number: '947',
    slug: 'most-stones-removed-with-same-row-or-column',
    title: '移除最多的同行或同列石头',
    difficulty: 'medium',
  },
  'lc:950': {
    id: 'lc:950',
    number: '950',
    slug: 'reveal-cards-in-increasing-order',
    title: '按递增顺序显示卡牌',
    difficulty: 'medium',
  },
  'lc:958': {
    id: 'lc:958',
    number: '958',
    slug: 'check-completeness-of-a-binary-tree',
    title: '二叉树的完全性检验',
    difficulty: 'medium',
  },
  'lc:967': {
    id: 'lc:967',
    number: '967',
    slug: 'numbers-with-same-consecutive-differences',
    title: '连续差相同的数字',
    difficulty: 'medium',
  },
  'lc:974': {
    id: 'lc:974',
    number: '974',
    slug: 'subarray-sums-divisible-by-k',
    title: '和可被 K 整除的子数组',
    difficulty: 'medium',
  },
  'lc:977': {
    id: 'lc:977',
    number: '977',
    slug: 'squares-of-a-sorted-array',
    title: '有序数组的平方',
    difficulty: 'easy',
  },
  'lc:980': {
    id: 'lc:980',
    number: '980',
    slug: 'unique-paths-iii',
    title: '不同路径 III',
    difficulty: 'hard',
  },
  'lc:988': {
    id: 'lc:988',
    number: '988',
    slug: 'smallest-string-starting-from-leaf',
    title: '从叶结点开始的最小字符串',
    difficulty: 'medium',
  },
  'lc:990': {
    id: 'lc:990',
    number: '990',
    slug: 'satisfiability-of-equality-equations',
    title: '等式方程的可满足性',
    difficulty: 'medium',
  },
  'lc:998': {
    id: 'lc:998',
    number: '998',
    slug: 'maximum-binary-tree-ii',
    title: '最大二叉树 II',
    difficulty: 'medium',
  },
  'lc:1004': {
    id: 'lc:1004',
    number: '1004',
    slug: 'max-consecutive-ones-iii',
    title: '最大连续1的个数 III',
    difficulty: 'medium',
  },
  'lc:1011': {
    id: 'lc:1011',
    number: '1011',
    slug: 'capacity-to-ship-packages-within-d-days',
    title: '在 D 天内送达包裹的能力',
    difficulty: 'medium',
  },
  'lc:1019': {
    id: 'lc:1019',
    number: '1019',
    slug: 'next-greater-node-in-linked-list',
    title: '链表中的下一个更大节点',
    difficulty: 'medium',
  },
  'lc:1020': {
    id: 'lc:1020',
    number: '1020',
    slug: 'number-of-enclaves',
    title: '飞地的数量',
    difficulty: 'medium',
  },
  'lc:1022': {
    id: 'lc:1022',
    number: '1022',
    slug: 'sum-of-root-to-leaf-binary-numbers',
    title: '从根到叶的二进制数之和',
    difficulty: 'easy',
  },
  'lc:1038': {
    id: 'lc:1038',
    number: '1038',
    slug: 'binary-search-tree-to-greater-sum-tree',
    title: '从二叉搜索树到更大和树',
    difficulty: 'medium',
  },
  'lc:1091': {
    id: 'lc:1091',
    number: '1091',
    slug: 'shortest-path-in-binary-matrix',
    title: '二进制矩阵中的最短路径',
    difficulty: 'medium',
  },
  'lc:1094': {
    id: 'lc:1094',
    number: '1094',
    slug: 'car-pooling',
    title: '拼车',
    difficulty: 'medium',
  },
  'lc:1109': {
    id: 'lc:1109',
    number: '1109',
    slug: 'corporate-flight-bookings',
    title: '航班预订统计',
    difficulty: 'medium',
  },
  'lc:1110': {
    id: 'lc:1110',
    number: '1110',
    slug: 'delete-nodes-and-return-forest',
    title: '删点成林',
    difficulty: 'medium',
  },
  'lc:1124': {
    id: 'lc:1124',
    number: '1124',
    slug: 'longest-well-performing-interval',
    title: '表现良好的最长时间段',
    difficulty: 'medium',
  },
  'lc:1135': {
    id: 'lc:1135',
    number: '1135',
    slug: 'connecting-cities-with-minimum-cost',
    title: '最低成本连通所有城市',
    difficulty: 'medium',
  },
  'lc:1143': {
    id: 'lc:1143',
    number: '1143',
    slug: 'longest-common-subsequence',
    title: '最长公共子序列',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:1161': {
    id: 'lc:1161',
    number: '1161',
    slug: 'maximum-level-sum-of-a-binary-tree',
    title: '最大层内元素和',
    difficulty: 'medium',
  },
  'lc:1201': {
    id: 'lc:1201',
    number: '1201',
    slug: 'ugly-number-iii',
    title: '丑数 III',
    difficulty: 'medium',
  },
  'lc:1235': {
    id: 'lc:1235',
    number: '1235',
    slug: 'maximum-profit-in-job-scheduling',
    title: '规划兼职工作',
    difficulty: 'hard',
  },
  'lc:1254': {
    id: 'lc:1254',
    number: '1254',
    slug: 'number-of-closed-islands',
    title: '统计封闭岛屿的数目',
    difficulty: 'medium',
  },
  'lc:1260': {
    id: 'lc:1260',
    number: '1260',
    slug: 'shift-2d-grid',
    title: '二维网格迁移',
    difficulty: 'easy',
  },
  'lc:1302': {
    id: 'lc:1302',
    number: '1302',
    slug: 'deepest-leaves-sum',
    title: '层数最深叶子节点的和',
    difficulty: 'medium',
  },
  'lc:1306': {
    id: 'lc:1306',
    number: '1306',
    slug: 'jump-game-iii',
    title: '跳跃游戏 III',
    difficulty: 'medium',
  },
  'lc:1312': {
    id: 'lc:1312',
    number: '1312',
    slug: 'minimum-insertion-steps-to-make-a-string-palindrome',
    title: '让字符串成为回文串的最少插入次数',
    difficulty: 'hard',
  },
  'lc:1314': {
    id: 'lc:1314',
    number: '1314',
    slug: 'matrix-block-sum',
    title: '矩阵区域和',
    difficulty: 'medium',
  },
  'lc:1329': {
    id: 'lc:1329',
    number: '1329',
    slug: 'sort-the-matrix-diagonally',
    title: '将矩阵按对角线排序',
    difficulty: 'medium',
  },
  'lc:1352': {
    id: 'lc:1352',
    number: '1352',
    slug: 'product-of-the-last-k-numbers',
    title: '最后 K 个数的乘积',
    difficulty: 'medium',
  },
  'lc:1361': {
    id: 'lc:1361',
    number: '1361',
    slug: 'validate-binary-tree-nodes',
    title: '验证二叉树',
    difficulty: 'medium',
  },
  'lc:1368': {
    id: 'lc:1368',
    number: '1368',
    slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid',
    title: '使网格图至少有一条有效路径的最小代价',
    difficulty: 'hard',
  },
  'lc:1373': {
    id: 'lc:1373',
    number: '1373',
    slug: 'maximum-sum-bst-in-binary-tree',
    title: '二叉搜索子树的最大键值和',
    difficulty: 'hard',
  },
  'lc:1425': {
    id: 'lc:1425',
    number: '1425',
    slug: 'constrained-subsequence-sum',
    title: '带限制的子序列和',
    difficulty: 'hard',
  },
  'lc:1438': {
    id: 'lc:1438',
    number: '1438',
    slug: 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit',
    title: '绝对差不超过限制的最长连续子数组',
    difficulty: 'medium',
  },
  'lc:1457': {
    id: 'lc:1457',
    number: '1457',
    slug: 'pseudo-palindromic-paths-in-a-binary-tree',
    title: '二叉树中的伪回文路径',
    difficulty: 'medium',
  },
  'lc:1475': {
    id: 'lc:1475',
    number: '1475',
    slug: 'final-prices-with-a-special-discount-in-a-shop',
    title: '商品折扣后的最终价格',
    difficulty: 'easy',
  },
  'lc:1514': {
    id: 'lc:1514',
    number: '1514',
    slug: 'path-with-maximum-probability',
    title: '概率最大的路径',
    difficulty: 'medium',
  },
  'lc:1584': {
    id: 'lc:1584',
    number: '1584',
    slug: 'min-cost-to-connect-all-points',
    title: '连接所有点的最小费用',
    difficulty: 'medium',
  },
  'lc:1609': {
    id: 'lc:1609',
    number: '1609',
    slug: 'even-odd-tree',
    title: '奇偶树',
    difficulty: 'medium',
  },
  'lc:1631': {
    id: 'lc:1631',
    number: '1631',
    slug: 'path-with-minimum-effort',
    title: '最小体力消耗路径',
    difficulty: 'medium',
  },
  'lc:1644': {
    id: 'lc:1644',
    number: '1644',
    slug: 'lowest-common-ancestor-of-a-binary-tree-ii',
    title: '二叉树的最近公共祖先 II',
    difficulty: 'medium',
  },
  'lc:1650': {
    id: 'lc:1650',
    number: '1650',
    slug: 'lowest-common-ancestor-of-a-binary-tree-iii',
    title: '二叉树的最近公共祖先 III',
    difficulty: 'medium',
  },
  'lc:1658': {
    id: 'lc:1658',
    number: '1658',
    slug: 'minimum-operations-to-reduce-x-to-zero',
    title: '将 x 减到 0 的最小操作数',
    difficulty: 'medium',
  },
  'lc:1670': {
    id: 'lc:1670',
    number: '1670',
    slug: 'design-front-middle-back-queue',
    title: '设计前中后队列',
    difficulty: 'medium',
  },
  'lc:1676': {
    id: 'lc:1676',
    number: '1676',
    slug: 'lowest-common-ancestor-of-a-binary-tree-iv',
    title: '二叉树的最近公共祖先 IV',
    difficulty: 'medium',
  },
  'lc:1696': {
    id: 'lc:1696',
    number: '1696',
    slug: 'jump-game-vi',
    title: '跳跃游戏 VI',
    difficulty: 'medium',
  },
  'lc:1700': {
    id: 'lc:1700',
    number: '1700',
    slug: 'number-of-students-unable-to-eat-lunch',
    title: '无法吃午餐的学生数量',
    difficulty: 'easy',
  },
  'lc:1804': {
    id: 'lc:1804',
    number: '1804',
    slug: 'implement-trie-ii-prefix-tree',
    title: '实现 Trie （前缀树） II',
    difficulty: 'medium',
  },
  'lc:1834': {
    id: 'lc:1834',
    number: '1834',
    slug: 'single-threaded-cpu',
    title: '单线程 CPU',
    difficulty: 'medium',
  },
  'lc:1845': {
    id: 'lc:1845',
    number: '1845',
    slug: 'seat-reservation-manager',
    title: '座位预约管理系统',
    difficulty: 'medium',
  },
  'lc:1905': {
    id: 'lc:1905',
    number: '1905',
    slug: 'count-sub-islands',
    title: '统计子岛屿',
    difficulty: 'medium',
  },
  'lc:1926': {
    id: 'lc:1926',
    number: '1926',
    slug: 'nearest-exit-from-entrance-in-maze',
    title: '迷宫中离入口最近的出口',
    difficulty: 'medium',
  },
  'lc:1944': {
    id: 'lc:1944',
    number: '1944',
    slug: 'number-of-visible-people-in-a-queue',
    title: '队列中可以看到的人数',
    difficulty: 'hard',
  },
  'lc:2073': {
    id: 'lc:2073',
    number: '2073',
    slug: 'time-needed-to-buy-tickets',
    title: '买票需要的时间',
    difficulty: 'easy',
  },
  'lc:lcr-038': {
    id: 'lc:lcr-038',
    number: 'LCR 038',
    slug: 'iIQa4I',
    title: '每日温度',
    difficulty: 'medium',
  },
  'lc:lcr-071': {
    id: 'lc:lcr-071',
    number: 'LCR 071',
    slug: 'cuyjEf',
    title: '按权重随机选择',
    difficulty: 'medium',
  },
  'lc:lcr-082': {
    id: 'lc:lcr-082',
    number: 'LCR 082',
    slug: '4sjJUc',
    title: '组合总和 II',
    difficulty: 'medium',
  },
  'lc:lcr-084': {
    id: 'lc:lcr-084',
    number: 'LCR 084',
    slug: '7p8L0Z',
    title: '全排列 II',
    difficulty: 'medium',
  },
  'lc:lcr-106': {
    id: 'lc:lcr-106',
    number: 'LCR 106',
    slug: 'vEAB3K',
    title: '判断二分图',
    difficulty: 'medium',
  },
  'lc:lcr-140': {
    id: 'lc:lcr-140',
    number: 'LCR 140',
    slug: 'lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof',
    title: '训练计划 II',
    difficulty: 'easy',
  },
  'lc:lcr-146': {
    id: 'lc:lcr-146',
    number: 'LCR 146',
    slug: 'shun-shi-zhen-da-yin-ju-zhen-lcof',
    title: '螺旋遍历二维数组',
    difficulty: 'easy',
  },
  'lc:lcr-172': {
    id: 'lc:lcr-172',
    number: 'LCR 172',
    slug: 'zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof',
    title: '统计目标成绩的出现次数',
    difficulty: 'easy',
  },
  'lc:lcr-184': {
    id: 'lc:lcr-184',
    number: 'LCR 184',
    slug: 'dui-lie-de-zui-da-zhi-lcof',
    title: '设计自助结算系统',
    difficulty: 'medium',
  },
}

const STUDY_PLAN_PROBLEMS: AlgorithmKnowledgeData['problems'] = {
  'lc:4': {
    id: 'lc:4',
    number: '4',
    slug: 'median-of-two-sorted-arrays',
    title: '寻找两个正序数组的中位数',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:6': {
    id: 'lc:6',
    number: '6',
    slug: 'zigzag-conversion',
    title: 'Z 字形变换',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:12': {
    id: 'lc:12',
    number: '12',
    slug: 'integer-to-roman',
    title: '整数转罗马数字',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:13': {
    id: 'lc:13',
    number: '13',
    slug: 'roman-to-integer',
    title: '罗马数字转整数',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:22': {
    id: 'lc:22',
    number: '22',
    slug: 'generate-parentheses',
    title: '括号生成',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:24': {
    id: 'lc:24',
    number: '24',
    slug: 'swap-nodes-in-pairs',
    title: '两两交换链表中的节点',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:28': {
    id: 'lc:28',
    number: '28',
    slug: 'find-the-index-of-the-first-occurrence-in-a-string',
    title: '找出字符串中第一个匹配项的下标',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:30': {
    id: 'lc:30',
    number: '30',
    slug: 'substring-with-concatenation-of-all-words',
    title: '串联所有单词的子串',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:31': {
    id: 'lc:31',
    number: '31',
    slug: 'next-permutation',
    title: '下一个排列',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:32': {
    id: 'lc:32',
    number: '32',
    slug: 'longest-valid-parentheses',
    title: '最长有效括号',
    difficulty: 'hard',
    tags: ['hot100'],
  },
  'lc:36': {
    id: 'lc:36',
    number: '36',
    slug: 'valid-sudoku',
    title: '有效的数独',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:41': {
    id: 'lc:41',
    number: '41',
    slug: 'first-missing-positive',
    title: '缺失的第一个正数',
    difficulty: 'hard',
    tags: ['hot100'],
  },
  'lc:56': {
    id: 'lc:56',
    number: '56',
    slug: 'merge-intervals',
    title: '合并区间',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:57': {
    id: 'lc:57',
    number: '57',
    slug: 'insert-interval',
    title: '插入区间',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:58': {
    id: 'lc:58',
    number: '58',
    slug: 'length-of-last-word',
    title: '最后一个单词的长度',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:62': {
    id: 'lc:62',
    number: '62',
    slug: 'unique-paths',
    title: '不同路径',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:63': {
    id: 'lc:63',
    number: '63',
    slug: 'unique-paths-ii',
    title: '不同路径 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:64': {
    id: 'lc:64',
    number: '64',
    slug: 'minimum-path-sum',
    title: '最小路径和',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:66': {
    id: 'lc:66',
    number: '66',
    slug: 'plus-one',
    title: '加一',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:68': {
    id: 'lc:68',
    number: '68',
    slug: 'text-justification',
    title: '文本左右对齐',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:69': {
    id: 'lc:69',
    number: '69',
    slug: 'sqrtx',
    title: 'x 的平方根',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:70': {
    id: 'lc:70',
    number: '70',
    slug: 'climbing-stairs',
    title: '爬楼梯',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:73': {
    id: 'lc:73',
    number: '73',
    slug: 'set-matrix-zeroes',
    title: '矩阵置零',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:84': {
    id: 'lc:84',
    number: '84',
    slug: 'largest-rectangle-in-histogram',
    title: '柱状图中最大的矩形',
    difficulty: 'hard',
    tags: ['hot100'],
  },
  'lc:97': {
    id: 'lc:97',
    number: '97',
    slug: 'interleaving-string',
    title: '交错字符串',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:100': {
    id: 'lc:100',
    number: '100',
    slug: 'same-tree',
    title: '相同的树',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:101': {
    id: 'lc:101',
    number: '101',
    slug: 'symmetric-tree',
    title: '对称二叉树',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:108': {
    id: 'lc:108',
    number: '108',
    slug: 'convert-sorted-array-to-binary-search-tree',
    title: '将有序数组转换为二叉搜索树',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:112': {
    id: 'lc:112',
    number: '112',
    slug: 'path-sum',
    title: '路径总和',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:118': {
    id: 'lc:118',
    number: '118',
    slug: 'pascals-triangle',
    title: '杨辉三角',
    difficulty: 'easy',
    tags: ['hot100'],
  },
  'lc:120': {
    id: 'lc:120',
    number: '120',
    slug: 'triangle',
    title: '三角形最小路径和',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:121': {
    id: 'lc:121',
    number: '121',
    slug: 'best-time-to-buy-and-sell-stock',
    title: '买卖股票的最佳时机',
    difficulty: 'easy',
    tags: ['hot100', 'interview150'],
  },
  'lc:122': {
    id: 'lc:122',
    number: '122',
    slug: 'best-time-to-buy-and-sell-stock-ii',
    title: '买卖股票的最佳时机 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:123': {
    id: 'lc:123',
    number: '123',
    slug: 'best-time-to-buy-and-sell-stock-iii',
    title: '买卖股票的最佳时机 III',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:124': {
    id: 'lc:124',
    number: '124',
    slug: 'binary-tree-maximum-path-sum',
    title: '二叉树中的最大路径和',
    difficulty: 'hard',
    tags: ['hot100', 'interview150'],
  },
  'lc:127': {
    id: 'lc:127',
    number: '127',
    slug: 'word-ladder',
    title: '单词接龙',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:135': {
    id: 'lc:135',
    number: '135',
    slug: 'candy',
    title: '分发糖果',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:137': {
    id: 'lc:137',
    number: '137',
    slug: 'single-number-ii',
    title: '只出现一次的数字 II',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:139': {
    id: 'lc:139',
    number: '139',
    slug: 'word-break',
    title: '单词拆分',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:148': {
    id: 'lc:148',
    number: '148',
    slug: 'sort-list',
    title: '排序链表',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:149': {
    id: 'lc:149',
    number: '149',
    slug: 'max-points-on-a-line',
    title: '直线上最多的点数',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:152': {
    id: 'lc:152',
    number: '152',
    slug: 'maximum-product-subarray',
    title: '乘积最大子数组',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:153': {
    id: 'lc:153',
    number: '153',
    slug: 'find-minimum-in-rotated-sorted-array',
    title: '寻找旋转排序数组中的最小值',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:173': {
    id: 'lc:173',
    number: '173',
    slug: 'binary-search-tree-iterator',
    title: '二叉搜索树迭代器',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:188': {
    id: 'lc:188',
    number: '188',
    slug: 'best-time-to-buy-and-sell-stock-iv',
    title: '买卖股票的最佳时机 IV',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:189': {
    id: 'lc:189',
    number: '189',
    slug: 'rotate-array',
    title: '轮转数组',
    difficulty: 'medium',
    tags: ['hot100', 'interview150'],
  },
  'lc:190': {
    id: 'lc:190',
    number: '190',
    slug: 'reverse-bits',
    title: '颠倒二进制位',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:191': {
    id: 'lc:191',
    number: '191',
    slug: 'number-of-1-bits',
    title: '位 1 的个数',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:201': {
    id: 'lc:201',
    number: '201',
    slug: 'bitwise-and-of-numbers-range',
    title: '数字范围按位与',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:202': {
    id: 'lc:202',
    number: '202',
    slug: 'happy-number',
    title: '快乐数',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:205': {
    id: 'lc:205',
    number: '205',
    slug: 'isomorphic-strings',
    title: '同构字符串',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:212': {
    id: 'lc:212',
    number: '212',
    slug: 'word-search-ii',
    title: '单词搜索 II',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:221': {
    id: 'lc:221',
    number: '221',
    slug: 'maximal-square',
    title: '最大正方形',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:228': {
    id: 'lc:228',
    number: '228',
    slug: 'summary-ranges',
    title: '汇总区间',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:274': {
    id: 'lc:274',
    number: '274',
    slug: 'h-index',
    title: 'H 指数',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:287': {
    id: 'lc:287',
    number: '287',
    slug: 'find-the-duplicate-number',
    title: '寻找重复数',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:289': {
    id: 'lc:289',
    number: '289',
    slug: 'game-of-life',
    title: '生命游戏',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:380': {
    id: 'lc:380',
    number: '380',
    slug: 'insert-delete-getrandom-o1',
    title: 'O(1) 时间插入、删除和获取随机元素',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:383': {
    id: 'lc:383',
    number: '383',
    slug: 'ransom-note',
    title: '赎金信',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:394': {
    id: 'lc:394',
    number: '394',
    slug: 'decode-string',
    title: '字符串解码',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:399': {
    id: 'lc:399',
    number: '399',
    slug: 'evaluate-division',
    title: '除法求值',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:427': {
    id: 'lc:427',
    number: '427',
    slug: 'construct-quad-tree',
    title: '建立四叉树',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:437': {
    id: 'lc:437',
    number: '437',
    slug: 'path-sum-iii',
    title: '路径总和 III',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:502': {
    id: 'lc:502',
    number: '502',
    slug: 'ipo',
    title: 'IPO',
    difficulty: 'hard',
    tags: ['interview150'],
  },
  'lc:530': {
    id: 'lc:530',
    number: '530',
    slug: 'minimum-absolute-difference-in-bst',
    title: '二叉搜索树的最小绝对差',
    difficulty: 'easy',
    tags: ['interview150'],
  },
  'lc:763': {
    id: 'lc:763',
    number: '763',
    slug: 'partition-labels',
    title: '划分字母区间',
    difficulty: 'medium',
    tags: ['hot100'],
  },
  'lc:909': {
    id: 'lc:909',
    number: '909',
    slug: 'snakes-and-ladders',
    title: '蛇梯棋',
    difficulty: 'medium',
    tags: ['interview150'],
  },
  'lc:994': {
    id: 'lc:994',
    number: '994',
    slug: 'rotting-oranges',
    title: '腐烂的橘子',
    difficulty: 'medium',
    tags: ['hot100'],
  },
}

const KNOWLEDGE_PROBLEMS: AlgorithmKnowledgeData['problems'] = {
  ...KNOWLEDGE_PROBLEMS_BASE,
  ...STUDY_PLAN_PROBLEMS,
}

export const ALGORITHM_KNOWLEDGE: AlgorithmKnowledgeData = {
  version: 2,
  groups: KNOWLEDGE_GROUPS,
  topics: KNOWLEDGE_TOPICS,
  problems: KNOWLEDGE_PROBLEMS,
}
