import type { FallbackEdge, FallbackNode, NodeKind, WorkflowEdge, WorkflowNode } from '@/types/web-pipeline'

export const WEB_PIPELINE_NODE_WIDTH = 214
export const WEB_PIPELINE_NODE_HEIGHT = 58
export const WEB_PIPELINE_FALLBACK_WIDTH = 7400
export const WEB_PIPELINE_FALLBACK_HEIGHT = 980
export const WEB_PIPELINE_FALLBACK_NODE_WIDTH = 176
export const WEB_PIPELINE_FALLBACK_NODE_HEIGHT = 44

export const WEB_PIPELINE_KIND_LABELS: Record<NodeKind, string> = {
  entry: '入口',
  cache: '缓存',
  network: '网络',
  server: '服务端',
  render: '渲染',
  perf: '优化',
}

export const WEB_PIPELINE_NODES: WorkflowNode[] = [
  {
    id: 'nav-start',
    title: '导航开始',
    kind: 'entry',
    stage: 0,
    lane: 2,
  },
  {
    id: 'sw-check',
    title: 'Service Worker 拦截',
    kind: 'cache',
    stage: 1,
    lane: 2,
  },
  {
    id: 'memory-cache',
    title: '内存缓存检查',
    kind: 'cache',
    stage: 2,
    lane: 1,
  },
  {
    id: 'disk-cache',
    title: '磁盘缓存检查',
    kind: 'cache',
    stage: 3,
    lane: 3,
  },
  {
    id: 'cdn-edge',
    title: 'CDN 边缘节点',
    kind: 'cache',
    stage: 4,
    lane: 2,
  },
  {
    id: 'dns-browser-cache',
    title: '浏览器 DNS 缓存',
    kind: 'network',
    stage: 5,
    lane: 1,
  },
  {
    id: 'dns-os-cache',
    title: '系统 DNS 缓存',
    kind: 'network',
    stage: 6,
    lane: 1,
  },
  {
    id: 'dns-hosts',
    title: 'Hosts 文件匹配',
    kind: 'network',
    stage: 7,
    lane: 1,
  },
  {
    id: 'dns-resolver',
    title: '递归 DNS 解析器',
    kind: 'network',
    stage: 8,
    lane: 2,
  },
  {
    id: 'dns-root',
    title: '根域名服务器',
    kind: 'network',
    stage: 9,
    lane: 1,
  },
  {
    id: 'dns-tld',
    title: '顶级域服务器',
    kind: 'network',
    stage: 10,
    lane: 1,
  },
  {
    id: 'dns-authoritative',
    title: '权威 DNS 服务器',
    kind: 'network',
    stage: 11,
    lane: 1,
  },
  {
    id: 'dns-result',
    title: '返回 IP 并写入缓存',
    kind: 'network',
    stage: 12,
    lane: 2,
  },
  {
    id: 'tcp-tls',
    title: 'TCP/TLS 建连',
    kind: 'network',
    stage: 13,
    lane: 2,
  },
  {
    id: 'http-request',
    title: '发送 HTTP 请求',
    kind: 'network',
    stage: 14,
    lane: 2,
  },
  {
    id: 'origin-response',
    title: '源站返回响应',
    kind: 'server',
    stage: 15,
    lane: 2,
  },
  {
    id: 'response-stream',
    title: '响应流接收',
    kind: 'render',
    stage: 16,
    lane: 2,
  },
  {
    id: 'html-parser',
    title: 'HTML 解析与 DOM',
    kind: 'render',
    stage: 17,
    lane: 1,
  },
  {
    id: 'cssom-js',
    title: 'CSSOM 构建与脚本执行',
    kind: 'render',
    stage: 17,
    lane: 3,
  },
  {
    id: 'render-tree',
    title: '构建渲染树',
    kind: 'render',
    stage: 18,
    lane: 2,
  },
  {
    id: 'layout',
    title: '布局计算（Layout）',
    kind: 'render',
    stage: 19,
    lane: 2,
  },
  {
    id: 'paint',
    title: '绘制（Paint）',
    kind: 'render',
    stage: 20,
    lane: 2,
  },
  {
    id: 'composite',
    title: '合成（Composite）',
    kind: 'render',
    stage: 21,
    lane: 2,
  },
  {
    id: 'cache-policy',
    title: '缓存策略优化',
    kind: 'perf',
    stage: 2,
    lane: 0,
  },
  {
    id: 'resource-hints',
    title: '资源预提示优化',
    kind: 'perf',
    stage: 10,
    lane: 0,
  },
  {
    id: 'render-opt',
    title: '渲染阶段优化',
    kind: 'perf',
    stage: 19,
    lane: 4,
  },
  {
    id: 'parse-blocking',
    title: '解析阻塞治理',
    kind: 'perf',
    stage: 17,
    lane: 5,
  },
  {
    id: 'forced-layout',
    title: '强制布局与回流治理',
    kind: 'perf',
    stage: 20,
    lane: 5,
  },
  {
    id: 'perf-metrics',
    title: '性能监控指标体系',
    kind: 'perf',
    stage: 22,
    lane: 0,
  },
  {
    id: 'engineering-pipeline',
    title: '前端工程化实践',
    kind: 'perf',
    stage: 23,
    lane: 1,
  },
  {
    id: 'html-strategy',
    title: 'HTML 加载与语义策略',
    kind: 'perf',
    stage: 23,
    lane: 2,
  },
  {
    id: 'css-strategy',
    title: 'CSS 架构与渲染策略',
    kind: 'perf',
    stage: 23,
    lane: 3,
  },
  {
    id: 'js-runtime',
    title: 'JavaScript 执行与调度',
    kind: 'perf',
    stage: 23,
    lane: 4,
  },
]

export const WEB_PIPELINE_EDGES: WorkflowEdge[] = [
  { source: 'nav-start', target: 'sw-check', label: '发起导航请求', kind: 'normal' },
  { source: 'sw-check', target: 'response-stream', label: '命中 SW 缓存', kind: 'hit' },
  { source: 'sw-check', target: 'memory-cache', label: 'SW 未命中', kind: 'miss' },
  { source: 'memory-cache', target: 'response-stream', label: '命中内存缓存', kind: 'hit' },
  { source: 'memory-cache', target: 'disk-cache', label: '内存缓存未命中', kind: 'miss' },
  { source: 'disk-cache', target: 'response-stream', label: '命中磁盘缓存 / 304 复用', kind: 'hit' },
  { source: 'disk-cache', target: 'cdn-edge', label: '磁盘缓存未命中', kind: 'miss' },
  { source: 'cdn-edge', target: 'response-stream', label: '命中 CDN 边缘缓存', kind: 'hit' },
  { source: 'cdn-edge', target: 'dns-browser-cache', label: 'CDN 未命中，进入 DNS', kind: 'miss' },
  { source: 'dns-browser-cache', target: 'tcp-tls', label: '浏览器 DNS 命中', kind: 'hit' },
  { source: 'dns-browser-cache', target: 'dns-os-cache', label: '浏览器 DNS 未命中', kind: 'miss' },
  { source: 'dns-os-cache', target: 'tcp-tls', label: '系统 DNS 命中', kind: 'hit' },
  { source: 'dns-os-cache', target: 'dns-hosts', label: '系统 DNS 未命中', kind: 'miss' },
  { source: 'dns-hosts', target: 'tcp-tls', label: '命中 hosts 映射', kind: 'hit' },
  { source: 'dns-hosts', target: 'dns-resolver', label: 'hosts 未命中', kind: 'miss' },
  { source: 'dns-resolver', target: 'dns-root', label: '递归查询开始', kind: 'normal' },
  { source: 'dns-root', target: 'dns-tld', label: '返回顶级域线索', kind: 'normal' },
  { source: 'dns-tld', target: 'dns-authoritative', label: '返回权威 DNS', kind: 'normal' },
  { source: 'dns-authoritative', target: 'dns-result', label: '返回最终记录', kind: 'validate' },
  { source: 'dns-result', target: 'tcp-tls', label: '拿到目标 IP', kind: 'normal' },
  { source: 'tcp-tls', target: 'http-request', label: '连接建立完成', kind: 'normal' },
  { source: 'http-request', target: 'origin-response', label: '请求已发送', kind: 'normal' },
  { source: 'origin-response', target: 'response-stream', label: '200 / 304 / 206', kind: 'validate' },
  { source: 'response-stream', target: 'html-parser', label: '流式解析 HTML', kind: 'normal' },
  { source: 'response-stream', target: 'cssom-js', label: '预加载扫描', kind: 'normal' },
  { source: 'html-parser', target: 'render-tree', label: 'DOM 就绪', kind: 'normal' },
  { source: 'cssom-js', target: 'render-tree', label: 'CSSOM 与脚本就绪', kind: 'normal' },
  { source: 'render-tree', target: 'layout', label: '计算布局几何', kind: 'normal' },
  { source: 'layout', target: 'paint', label: '生成绘制指令', kind: 'normal' },
  { source: 'paint', target: 'composite', label: '图层合成输出', kind: 'normal' },
  { source: 'cache-policy', target: 'memory-cache', label: 'Cache-Control / ETag', kind: 'optimize' },
  { source: 'cache-policy', target: 'disk-cache', label: '协商缓存策略', kind: 'optimize' },
  { source: 'cache-policy', target: 'cdn-edge', label: 'CDN TTL 与回源策略', kind: 'optimize' },
  { source: 'resource-hints', target: 'dns-browser-cache', label: 'dns-prefetch', kind: 'optimize' },
  { source: 'resource-hints', target: 'tcp-tls', label: 'preconnect', kind: 'optimize' },
  { source: 'resource-hints', target: 'response-stream', label: 'preload 关键资源', kind: 'optimize' },
  { source: 'parse-blocking', target: 'response-stream', label: '预加载扫描治理', kind: 'optimize' },
  { source: 'parse-blocking', target: 'html-parser', label: 'HTML 解析阻塞治理', kind: 'optimize' },
  { source: 'parse-blocking', target: 'cssom-js', label: 'CSS/JS 阻塞治理', kind: 'optimize' },
  { source: 'render-opt', target: 'layout', label: 'contain / content-visibility', kind: 'optimize' },
  { source: 'render-opt', target: 'paint', label: '缩小重绘区域', kind: 'optimize' },
  { source: 'forced-layout', target: 'cssom-js', label: '批量读写 DOM', kind: 'optimize' },
  { source: 'forced-layout', target: 'layout', label: '避免强制同步布局', kind: 'optimize' },
  { source: 'forced-layout', target: 'paint', label: '减少回流重绘', kind: 'optimize' },
  { source: 'perf-metrics', target: 'tcp-tls', label: '网络阶段指标', kind: 'optimize' },
  { source: 'perf-metrics', target: 'origin-response', label: '服务端与 TTFB', kind: 'optimize' },
  { source: 'perf-metrics', target: 'layout', label: 'CWV 与渲染指标', kind: 'optimize' },
  { source: 'perf-metrics', target: 'composite', label: '帧率与长任务', kind: 'optimize' },
  { source: 'engineering-pipeline', target: 'cache-policy', label: '构建产物可缓存性', kind: 'optimize' },
  { source: 'engineering-pipeline', target: 'resource-hints', label: '资源拆分与预加载', kind: 'optimize' },
  { source: 'engineering-pipeline', target: 'perf-metrics', label: 'CI 性能门禁与监控', kind: 'optimize' },
  { source: 'html-strategy', target: 'nav-start', label: '语义结构与可访问性', kind: 'optimize' },
  { source: 'html-strategy', target: 'html-parser', label: '减少解析阻塞点', kind: 'optimize' },
  { source: 'html-strategy', target: 'parse-blocking', label: '首屏关键 HTML 组织', kind: 'optimize' },
  { source: 'css-strategy', target: 'cssom-js', label: '样式架构与选择器成本', kind: 'optimize' },
  { source: 'css-strategy', target: 'layout', label: '布局策略与稳定性', kind: 'optimize' },
  { source: 'css-strategy', target: 'paint', label: '重绘区域治理', kind: 'optimize' },
  { source: 'js-runtime', target: 'cssom-js', label: '脚本执行时机治理', kind: 'optimize' },
  { source: 'js-runtime', target: 'forced-layout', label: '避免读写交错', kind: 'optimize' },
  { source: 'js-runtime', target: 'perf-metrics', label: '长任务与交互延迟', kind: 'optimize' },
]

export const WEB_PIPELINE_FALLBACK_NODES: FallbackNode[] = WEB_PIPELINE_NODES.map(node => ({
  id: node.id,
  title: node.title,
  kind: node.kind,
  x: 96 + node.stage * 308 + WEB_PIPELINE_FALLBACK_NODE_WIDTH / 2,
  y: 72 + node.lane * 154 + WEB_PIPELINE_FALLBACK_NODE_HEIGHT / 2,
}))

const fallbackNodeMap = new Map(WEB_PIPELINE_FALLBACK_NODES.map(node => [node.id, node]))

export const WEB_PIPELINE_FALLBACK_EDGES: FallbackEdge[] = WEB_PIPELINE_EDGES.flatMap((edge) => {
  const sourceNode = fallbackNodeMap.get(edge.source)
  const targetNode = fallbackNodeMap.get(edge.target)
  if (!sourceNode || !targetNode)
    return []
  return [{ ...edge, sourceNode, targetNode }]
})

export const WEB_PIPELINE_NODE_MAP = new Map(WEB_PIPELINE_NODES.map(node => [node.id, node]))
