/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./../components/back.vue')['default']
    Bluesky: typeof import('./../components/bluesky.vue')['default']
    DarkToggle: typeof import('./../components/dark-toggle.vue')['default']
    Footer: typeof import('./../components/footer.vue')['default']
    Github: typeof import('./../components/github.vue')['default']
    Layout: typeof import('./../components/layout.vue')['default']
    Noise: typeof import('./../components/noise.vue')['default']
    ProjectCard: typeof import('./../components/project-card.vue')['default']
    Prose: typeof import('./../components/prose.vue')['default']
    PullRequest: typeof import('./../components/pull-request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Twitter: typeof import('./../components/twitter.vue')['default']
  }
}
