/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./../components/back.vue')['default']
    Bluesky: typeof import('./../components/bluesky.vue')['default']
    DarkToggle: typeof import('./../components/dark-toggle.vue')['default']
    Footer: typeof import('./../components/footer.vue')['default']
    Github: typeof import('./../components/github.vue')['default']
    GithubStats: typeof import('./../components/github-stats.vue')['default']
    Mermaid: typeof import('./../components/mermaid.vue')['default']
    Noise: typeof import('./../components/noise.vue')['default']
    PostList: typeof import('./../components/post-list.vue')['default']
    PrintButton: typeof import('./../components/print-button.vue')['default']
    ProjectCard: typeof import('./../components/project-card.vue')['default']
    PullRequest: typeof import('./../components/pull-request.vue')['default']
    RankChart: typeof import('./../components/rank-chart.vue')['default']
    Spinner: typeof import('./../components/spinner.vue')['default']
    Twitter: typeof import('./../components/twitter.vue')['default']
  }
}
